# Generated by Django 6.0.1 on 2026-04-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_registry', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherMaterialLawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Представитель в ином материале',
                'verbose_name_plural': 'Представители в иных материалах',
            },
        ),
        migrations.CreateModel(
            name='OtherMaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Движение иного материала',
                'verbose_name_plural': 'Движения иных материалов',
                'ordering': ['-business_movement__date_meeting', '-business_movement__meeting_time'],
            },
        ),
        migrations.CreateModel(
            name='OtherMaterialPetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petitioner_type', models.CharField(blank=True, choices=[('other_sides', 'Сторона'), ('other_lawyer', 'Представитель')], max_length=20, null=True, verbose_name='Тип заявителя')),
                ('petitioner_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID заявителя')),
            ],
            options={
                'verbose_name': 'Ходатайство/заявление в ином материале',
                'verbose_name_plural': 'Ходатайства/заявления в иных материалах',
            },
        ),
        migrations.CreateModel(
            name='OtherMaterialSidesCaseInCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Сторона иного материала',
                'verbose_name_plural': 'Стороны иного материала',
            },
        ),
        migrations.CreateModel(
            name='OtherMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100, unique=True, verbose_name='Регистрационный номер')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование материала')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание/содержание')),
                ('incoming_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Входящий номер')),
                ('incoming_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления')),
                ('sender', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отправитель')),
                ('consideration_date', models.DateField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('consideration_result', models.TextField(blank=True, null=True, verbose_name='Результат рассмотрения')),
                ('status', models.CharField(choices=[('active', 'Активное'), ('completed', 'Завершено'), ('archived', 'В архиве')], default='active', max_length=20, verbose_name='Статус')),
                ('archived_date', models.DateField(blank=True, null=True, verbose_name='Дата сдачи в архив')),
                ('archive_notes', models.TextField(blank=True, null=True, verbose_name='Примечания по архивному делу')),
                ('special_notes', models.TextField(blank=True, null=True, verbose_name='Особые отметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_material_link', to='case_registry.registeredcase', verbose_name='Зарегистрированное дело')),
            ],
            options={
                'verbose_name': 'Иной материал',
                'verbose_name_plural': 'Иные материалы',
                'ordering': ['-registration_date', '-created_at'],
            },
        ),
    ]
