# Generated by Django 6.0.1 on 2026-04-13 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_card', '0002_initial'),
        ('case_registry', '0004_alter_correspondence_registration_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100, unique=True, verbose_name='Регистрационный номер')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование материала')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание/содержание')),
                ('incoming_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Входящий номер')),
                ('incoming_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления')),
                ('sender', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отправитель')),
                ('consideration_date', models.DateField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('consideration_result', models.TextField(blank=True, null=True, verbose_name='Результат рассмотрения')),
                ('status', models.CharField(choices=[('active', 'Активное'), ('completed', 'Завершено'), ('archived', 'В архиве')], default='active', max_length=20, verbose_name='Статус')),
                ('archived_date', models.DateField(blank=True, null=True, verbose_name='Дата сдачи в архив')),
                ('archive_notes', models.TextField(blank=True, null=True, verbose_name='Примечания по архивному делу')),
                ('special_notes', models.TextField(blank=True, null=True, verbose_name='Особые отметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_material_link', to='case_registry.registeredcase', verbose_name='Зарегистрированное дело')),
                ('responsible_person', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['judge', 'secretary', 'assistant']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Иной материал',
                'verbose_name_plural': 'Иные материалы',
                'ordering': ['-registration_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtherMaterialLawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_material_lawyers', to='business_card.lawyer', verbose_name='Представитель (данные из business_card)')),
                ('other_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_lawyers', to='other_materials.othermaterial', verbose_name='Иной материал')),
                ('sides_case_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_material_lawyers', to='business_card.sidescase', verbose_name='Представитель какой стороны')),
            ],
            options={
                'verbose_name': 'Представитель в ином материале',
                'verbose_name_plural': 'Представители в иных материалах',
            },
        ),
        migrations.CreateModel(
            name='OtherMaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_material_movements', to='business_card.businessmovement', verbose_name='Движение (из business_card)')),
                ('other_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_movements', to='other_materials.othermaterial', verbose_name='Иной материал')),
            ],
            options={
                'verbose_name': 'Движение иного материала',
                'verbose_name_plural': 'Движения иных материалов',
                'ordering': ['-business_movement__date_meeting', '-business_movement__meeting_time'],
            },
        ),
        migrations.CreateModel(
            name='OtherMaterialPetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petitioner_type', models.CharField(blank=True, choices=[('other_sides', 'Сторона'), ('other_lawyer', 'Представитель')], max_length=20, null=True, verbose_name='Тип заявителя')),
                ('petitioner_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID заявителя')),
                ('other_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_petitions', to='other_materials.othermaterial', verbose_name='Иной материал')),
                ('petitions_incase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_material_petitions', to='business_card.petitionsincase', verbose_name='Ходатайство/заявление')),
            ],
            options={
                'verbose_name': 'Ходатайство/заявление в ином материале',
                'verbose_name_plural': 'Ходатайства/заявления в иных материалах',
                'indexes': [models.Index(fields=['petitioner_type', 'petitioner_id'], name='other_mater_petitio_9d8adf_idx')],
            },
        ),
        migrations.CreateModel(
            name='OtherMaterialSidesCaseInCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_sides', to='other_materials.othermaterial', verbose_name='Иной материал')),
                ('sides_case_incase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_material_sides', to='business_card.sidescaseincase', verbose_name='Данные стороны (ФИО/наименование, контакты)')),
                ('sides_case_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_material_sides', to='business_card.sidescase', verbose_name='Роль стороны')),
            ],
            options={
                'verbose_name': 'Сторона иного материала',
                'verbose_name_plural': 'Стороны иного материала',
                'unique_together': {('other_material', 'sides_case_incase', 'sides_case_role')},
            },
        ),
    ]
