# Generated by Django 6.0.1 on 2026-04-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_card', '0002_initial'),
        ('other_materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='othermaterial',
            name='responsible_person',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['judge', 'secretary', 'assistant']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='othermateriallawyer',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_material_lawyers', to='business_card.lawyer', verbose_name='Представитель (данные из business_card)'),
        ),
        migrations.AddField(
            model_name='othermateriallawyer',
            name='other_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_lawyers', to='other_materials.othermaterial', verbose_name='Иной материал'),
        ),
        migrations.AddField(
            model_name='othermateriallawyer',
            name='sides_case_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_material_lawyers', to='business_card.sidescase', verbose_name='Представитель какой стороны'),
        ),
        migrations.AddField(
            model_name='othermaterialmovement',
            name='business_movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_material_movements', to='business_card.businessmovement', verbose_name='Движение (из business_card)'),
        ),
        migrations.AddField(
            model_name='othermaterialmovement',
            name='other_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_movements', to='other_materials.othermaterial', verbose_name='Иной материал'),
        ),
        migrations.AddField(
            model_name='othermaterialpetition',
            name='other_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_petitions', to='other_materials.othermaterial', verbose_name='Иной материал'),
        ),
        migrations.AddField(
            model_name='othermaterialpetition',
            name='petitions_incase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_material_petitions', to='business_card.petitionsincase', verbose_name='Ходатайство/заявление'),
        ),
        migrations.AddField(
            model_name='othermaterialsidescaseincase',
            name='other_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_sides', to='other_materials.othermaterial', verbose_name='Иной материал'),
        ),
        migrations.AddField(
            model_name='othermaterialsidescaseincase',
            name='sides_case_incase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_material_sides', to='business_card.sidescaseincase', verbose_name='Данные стороны (ФИО/наименование, контакты)'),
        ),
        migrations.AddField(
            model_name='othermaterialsidescaseincase',
            name='sides_case_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_material_sides', to='business_card.sidescase', verbose_name='Роль стороны'),
        ),
        migrations.AddIndex(
            model_name='othermaterialpetition',
            index=models.Index(fields=['petitioner_type', 'petitioner_id'], name='other_mater_petitio_9d8adf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='othermaterialsidescaseincase',
            unique_together={('other_material', 'sides_case_incase', 'sides_case_role')},
        ),
    ]
