# Generated by Django 6.0.1 on 2026-04-20 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_materials', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherMaterialDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(blank=True, choices=[('1', 'Удовлетворено'), ('2', 'Отказано в удовлетворении'), ('3', 'Прекращено производство'), ('4', 'Оставлено без рассмотрения'), ('5', 'Передано по подведомственности')], max_length=255, null=True, verbose_name='Результат рассмотрения')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='Дата вынесения решения')),
                ('decision_effective_date', models.DateField(blank=True, null=True, verbose_name='Дата вступления в силу')),
                ('complaint_filed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Подана жалоба')),
                ('complaint_result', models.CharField(blank=True, choices=[('1', 'Оставлено без изменения'), ('2', 'Отменено'), ('3', 'Изменено')], max_length=255, null=True, verbose_name='Результат обжалования')),
                ('other_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_decisions', to='other_materials.othermaterial', verbose_name='Иной материал')),
            ],
            options={
                'verbose_name': 'Решение по иному материалу',
                'verbose_name_plural': 'Решения по иным материалам',
                'ordering': ['-decision_date'],
            },
        ),
        migrations.CreateModel(
            name='OtherMaterialExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_document_date', models.DateField(blank=True, null=True, verbose_name='Дата исполнительного документа')),
                ('execution_document_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер исполнительного документа')),
                ('executed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Исполнено')),
                ('execution_date', models.DateField(blank=True, null=True, verbose_name='Дата фактического исполнения')),
                ('execution_result', models.CharField(blank=True, choices=[('1', 'Исполнено полностью'), ('2', 'Не исполнено'), ('3', 'Частично исполнено')], max_length=255, null=True, verbose_name='Результат исполнения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания по исполнению')),
                ('other_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_executions', to='other_materials.othermaterial', verbose_name='Иной материал')),
            ],
            options={
                'verbose_name': 'Исполнение по иному материалу',
                'verbose_name_plural': 'Исполнения по иным материалам',
                'ordering': ['-execution_document_date'],
            },
        ),
    ]
