# Generated by Django 6.0.1 on 2026-04-22 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_registry', '0003_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('other_materials', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherMaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование вида иного материала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Вид иного материала',
                'verbose_name_plural': 'Виды иных материалов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='othermaterialexecution',
            name='other_material',
        ),
        migrations.RemoveField(
            model_name='othermaterialmovement',
            name='business_movement',
        ),
        migrations.RemoveField(
            model_name='othermaterialmovement',
            name='other_material',
        ),
        migrations.RemoveIndex(
            model_name='othermaterialpetition',
            name='other_mater_petitio_9d8adf_idx',
        ),
        migrations.RemoveField(
            model_name='othermaterial',
            name='consideration_result',
        ),
        migrations.AddField(
            model_name='othermaterial',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'app_label__in': ['civil_proceedings', 'criminal_proceedings', 'administrative_proceedings', 'kas_proceedings'], 'model__in': ['civilproceedings', 'criminalproceedings', 'administrativeproceedings', 'kasproceedings']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип связанного дела'),
        ),
        migrations.AddField(
            model_name='othermaterial',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанного дела'),
        ),
        migrations.AddField(
            model_name='othermaterial',
            name='outcome',
            field=models.CharField(blank=True, choices=[('satisfied', 'Удовлетворено'), ('rejected', 'Отказано в удовлетворении'), ('dismissed', 'Прекращено производство'), ('left_without', 'Оставлено без рассмотрения'), ('transferred', 'Передано по подсудности/подведомственности')], max_length=20, null=True, verbose_name='Результат рассмотрения'),
        ),
        migrations.AddField(
            model_name='othermaterial',
            name='outcome_details',
            field=models.TextField(blank=True, help_text='Подробное описание результата рассмотрения', null=True, verbose_name='Детали результата'),
        ),
        migrations.AddField(
            model_name='othermaterial',
            name='related_case_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер связанного дела'),
        ),
        migrations.AlterField(
            model_name='othermaterial',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание материала'),
        ),
        migrations.AlterField(
            model_name='othermaterial',
            name='registered_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_material_link_old', to='case_registry.registeredcase', verbose_name='Зарегистрированное дело (устаревшее)'),
        ),
        migrations.AlterField(
            model_name='othermaterial',
            name='sender',
            field=models.CharField(blank=True, help_text='Наименование организации или ФИО отправителя', max_length=500, null=True, verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='othermaterial',
            name='material_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='other_materials.othermaterialtype', verbose_name='Вид иного материала'),
        ),
        migrations.AddIndex(
            model_name='othermaterial',
            index=models.Index(fields=['registration_number'], name='other_mater_registr_bc589f_idx'),
        ),
        migrations.AddIndex(
            model_name='othermaterial',
            index=models.Index(fields=['status'], name='other_mater_status_c0625c_idx'),
        ),
        migrations.AddIndex(
            model_name='othermaterial',
            index=models.Index(fields=['content_type', 'object_id'], name='other_mater_content_15cac9_idx'),
        ),
        migrations.AddIndex(
            model_name='othermaterial',
            index=models.Index(fields=['material_type'], name='other_mater_materia_c2d428_idx'),
        ),
        migrations.AddIndex(
            model_name='othermaterial',
            index=models.Index(fields=['outcome'], name='other_mater_outcome_3bbb29_idx'),
        ),
        migrations.DeleteModel(
            name='OtherMaterialExecution',
        ),
        migrations.DeleteModel(
            name='OtherMaterialMovement',
        ),
        migrations.DeleteModel(
            name='OtherMaterialPetition',
        ),
    ]
