# Generated by Django 4.2.7 on 2025-09-03 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalProceedings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_persons', models.PositiveIntegerField(blank=True, null=True, verbose_name='Число лиц по делу')),
                ('evidence_present', models.BooleanField(blank=True, null=True, verbose_name='Наличие вещдоков')),
                ('evidence_reg_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Рег. номер вещдока')),
                ('incoming_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления дела в суд')),
                ('incoming_from', models.CharField(blank=True, max_length=255, null=True, verbose_name='Откуда поступило')),
                ('case_order', models.CharField(blank=True, max_length=255, null=True, verbose_name='Порядок поступления дела')),
                ('repeat_case', models.BooleanField(blank=True, null=True, verbose_name='Повторное поступление дела')),
                ('repeat_case_date', models.DateField(blank=True, null=True, verbose_name='Дата повторного поступления')),
                ('case_category_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория дела')),
                ('judge_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО судьи')),
                ('judge_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код судьи')),
                ('judge_acceptance_date', models.DateField(blank=True, null=True, verbose_name='Дата принятия дела судьей')),
                ('preliminary_hearing_date', models.DateField(blank=True, null=True, verbose_name='Дата предварительного слушания')),
                ('preliminary_hearing_result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат слушания')),
                ('first_hearing_date', models.DateField(blank=True, null=True, verbose_name='Дата первого заседания')),
                ('hearing_postponed_reason', models.TextField(blank=True, null=True, verbose_name='Причина отложения')),
                ('suspension_date', models.DateField(blank=True, null=True, verbose_name='Дата приостановления производства')),
                ('resumption_date', models.DateField(blank=True, null=True, verbose_name='Дата возобновления производства')),
                ('case_result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат рассмотрения дела в целом')),
                ('total_duration_days', models.IntegerField(blank=True, null=True, verbose_name='Общая продолжительность (дни)')),
                ('composition_court', models.CharField(blank=True, max_length=255, null=True, verbose_name='Состав суда')),
                ('participation_details', models.TextField(blank=True, null=True, verbose_name='Особенности участия (прокурор, переводчик и др.)')),
                ('sentence_date', models.DateField(blank=True, null=True, verbose_name='Дата вынесения приговора')),
                ('sentence_result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат рассмотрения (приговор, прекращение и др.)')),
                ('appeal_date', models.DateField(blank=True, null=True, verbose_name='Дата обжалования')),
                ('appeal_result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат обжалования')),
                ('cassation_date', models.DateField(blank=True, null=True, verbose_name='Дата кассации/надзора')),
                ('cassation_result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат кассации/надзора')),
                ('case_to_archive_date', models.DateField(blank=True, null=True, verbose_name='Дата сдачи дела в архив')),
                ('special_notes', models.TextField(blank=True, null=True, verbose_name='Особые отметки')),
                ('business_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_proceedings', to='business_card.businesscard', verbose_name='Базовая карточка')),
            ],
            options={
                'verbose_name': 'Уголовное производство',
                'verbose_name_plural': 'Уголовные производства',
            },
        ),
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО обвиняемого')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес проживания')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('sex', models.CharField(blank=True, max_length=10, null=True, verbose_name='Пол')),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Гражданство')),
                ('restraint_measure', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мера пресечения')),
                ('restraint_date', models.DateField(blank=True, null=True, verbose_name='Дата избрания меры пресечения')),
                ('trial_result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат рассмотрения по данному лицу')),
                ('conviction_article', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статья по приговору')),
                ('punishment_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид наказания')),
                ('punishment_term', models.CharField(blank=True, max_length=255, null=True, verbose_name='Срок наказания')),
                ('additional_punishment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительное наказание')),
                ('parole_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Условно-досрочное освобождение / испытательный срок')),
                ('property_damage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма ущерба')),
                ('moral_damage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма морального вреда')),
                ('special_notes', models.TextField(blank=True, null=True, verbose_name='Особые отметки по лицу')),
                ('criminal_proceedings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defendants', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство')),
            ],
            options={
                'verbose_name': 'Обвиняемый',
                'verbose_name_plural': 'Обвиняемые',
            },
        ),
    ]
