# Generated by Django 6.0.1 on 2026-04-22 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_card', '0002_initial'),
        ('case_registry', '0003_initial'),
        ('criminal_proceedings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalproceedings',
            name='presiding_judge',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'judge'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Председательствующий'),
        ),
        migrations.AddField(
            model_name='criminalproceedings',
            name='registered_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criminal_proceedings_link', to='case_registry.registeredcase', verbose_name='Зарегистрированное дело'),
        ),
        migrations.AddField(
            model_name='criminalpersoncard',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_cards', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='criminalexecution',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_executions', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='criminaldecision',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_decisions', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='criminalcivilclaim',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_claims', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='criminalcassationinstance',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cassation_instances', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='criminalcasemovement',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_movement', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='criminalappealinstance',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeal_instances', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='criminalruling',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulings', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='criminalsidescaseincase',
            name='criminal_proceedings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criminal_sides', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='criminalsidescaseincase',
            name='criminal_side_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criminal_sides', to='business_card.sidescaseincase', verbose_name='Стороны Уголовного производства'),
        ),
        migrations.AddField(
            model_name='criminalsidescaseincase',
            name='sides_case_criminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_SidesCase', to='business_card.sidescase', verbose_name='Сторона по делу'),
        ),
        migrations.AddField(
            model_name='defendant',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defendants', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='defendant',
            name='sides_case_defendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_defendants', to='business_card.sidescase', verbose_name='Подсудимый по делу'),
        ),
        migrations.AddField(
            model_name='criminalpersoncard',
            name='defendant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_card', to='criminal_proceedings.defendant', verbose_name='Подсудимый'),
        ),
        migrations.AddField(
            model_name='criminalexecution',
            name='criminal_defendant_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminal_proceedings.defendant', verbose_name='Приговор вступивший в законную силу вручен'),
        ),
        migrations.AddField(
            model_name='criminalcivilclaim',
            name='victim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civil_claims', to='criminal_proceedings.defendant', verbose_name='Потерпевший (истец)'),
        ),
        migrations.AddField(
            model_name='lawyercriminal',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_lawyers', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='lawyercriminal',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criminal_lawyers', to='business_card.lawyer', verbose_name='Адвокат'),
        ),
        migrations.AddField(
            model_name='lawyercriminal',
            name='sides_case_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criminal_lawyers', to='business_card.sidescase', verbose_name='Роль в деле'),
        ),
        migrations.AddField(
            model_name='petitioncriminal',
            name='criminal_proceedings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='petitioncriminal',
            name='petitions_criminal',
            field=models.ManyToManyField(related_name='criminal_petitions', to='business_card.petitions', verbose_name='ходатайства по делу'),
        ),
        migrations.AddField(
            model_name='petitioncriminal',
            name='petitions_incase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criminal_petitions', to='business_card.petitionsincase', verbose_name='Ходатайство в деле'),
        ),
        migrations.AddField(
            model_name='previousconviction',
            name='person_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_convictions', to='criminal_proceedings.criminalpersoncard', verbose_name='Карточка подсудимого'),
        ),
        migrations.AddField(
            model_name='criminalproceedings',
            name='referring_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='criminal_proceedings.referringauthority', verbose_name='Орган, направивший материалы'),
        ),
        migrations.AddField(
            model_name='sentencedpunishment',
            name='person_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='criminal_proceedings.criminalpersoncard', verbose_name='Карточка подсудимого'),
        ),
        migrations.AlterUniqueTogether(
            name='criminalpersoncard',
            unique_together={('defendant', 'criminal_proceedings')},
        ),
        migrations.AddIndex(
            model_name='petitioncriminal',
            index=models.Index(fields=['petitioner_type', 'petitioner_id'], name='criminal_pr_petitio_14971e_idx'),
        ),
    ]
