# Generated by Django 6.0.1 on 2026-01-27 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_card', '0002_initial'),
        ('criminal_proceedings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalproceedings',
            name='presiding_judge',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'judge'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Председательствующий'),
        ),
        migrations.AddField(
            model_name='criminaldecision',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_decisions', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='criminalcasemovement',
            name='criminal_proceedings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_movement', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='criminalruling',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulings', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='defendant',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defendants', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='defendant',
            name='sides_case_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_defendants', to='business_card.sidescaseincase', verbose_name='Сторона по делу'),
        ),
        migrations.AddField(
            model_name='criminalproceedings',
            name='referring_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='criminal_proceedings.referringauthority', verbose_name='Орган, направивший материалы'),
        ),
    ]
