# Generated by Django 4.2.7 on 2025-09-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_initial'),
        ('criminal_proceedings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defendant',
            name='sides_case',
            field=models.ManyToManyField(to='business_card.sidescase', verbose_name='Стороны по делу'),
        ),
    ]
