# Generated by Django 6.0.1 on 2026-02-05 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_card', '0002_initial'),
        ('criminal_proceedings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalproceedings',
            name='presiding_judge',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'judge'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Председательствующий'),
        ),
        migrations.AddField(
            model_name='criminaldecision',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_decisions', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='criminalcasemovement',
            name='criminal_proceedings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_movement', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='criminalruling',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulings', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='criminalsidescaseincase',
            name='criminal_proceedings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criminal_sides', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='criminalsidescaseincase',
            name='criminal_side_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criminal_sides', to='business_card.sidescaseincase', verbose_name='Стороны Уголовного производства'),
        ),
        migrations.AddField(
            model_name='criminalsidescaseincase',
            name='sides_case_criminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_SidesCase', to='business_card.sidescase', verbose_name='Сторона по делу'),
        ),
        migrations.AddField(
            model_name='defendant',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defendants', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='defendant',
            name='sides_case_defendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_defendants', to='business_card.sidescase', verbose_name='Подсудимый по делу'),
        ),
        migrations.AddField(
            model_name='lawyercriminal',
            name='criminal_proceedings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criminal_sides_lawyer', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='lawyercriminal',
            name='sides_case_lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_lawyer', to='business_card.sidescase', verbose_name='Адвокат по делу'),
        ),
        migrations.AddField(
            model_name='lawyercriminal',
            name='sides_case_lawyer_criminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_info', to='business_card.lawyer', verbose_name='Сторона (адвокат)'),
        ),
        migrations.AddField(
            model_name='criminalproceedings',
            name='referring_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='criminal_proceedings.referringauthority', verbose_name='Орган, направивший материалы'),
        ),
    ]
