# Generated by Django 4.2.7 on 2025-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_proceedings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalproceedings',
            name='preliminary_hearing',
            field=models.CharField(blank=True, choices=[('1', 'Ходатайство стороны об исключении доказательства'), ('2', 'Основание для возвращения дела прокурору (ст. 237 УПК РФ)'), ('3', 'Основание для приостановления или прекращения дела'), ('4', 'Ходатайство о проведении судебного разбирательства в особом порядке'), ('4', 'Решение вопроса о рассмотрении дела с участием присяжных заседателей'), ('4', 'Наличие не вступившего в законную силу приговора с условным осуждением'), ('4', 'Основание для выделения уголовного дела'), ('4', 'Ходатайство стороны о соединении уголовных дел')], max_length=255, null=True, verbose_name='Основания для предварительного слушания'),
        ),
    ]
