# Generated by Django 5.2.9 on 2026-01-02 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_proceedings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminalproceedings',
            name='judge_name',
        ),
        migrations.AddField(
            model_name='criminalproceedings',
            name='consideration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рассмотрения'),
        ),
        migrations.AddField(
            model_name='criminalproceedings',
            name='presiding_judge',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'judge'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Председательствующий'),
        ),
        migrations.AddField(
            model_name='criminalproceedings',
            name='referring_authority',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Орган, направивший материалы'),
        ),
        migrations.AddField(
            model_name='criminalproceedings',
            name='volume_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество томов'),
        ),
        migrations.AlterField(
            model_name='criminalproceedings',
            name='composition_court',
            field=models.CharField(blank=True, choices=[('1', 'единолично судьей'), ('2', 'коллегией судей'), ('3', 'с участием присяжных заседателей')], max_length=255, null=True, verbose_name='Состав суда'),
        ),
    ]
