# Generated by Django 4.2.7 on 2025-11-21 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_proceedings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalRuling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruling_type', models.CharField(choices=[('preliminary_hearing', 'О назначении предварительного слушания'), ('court_session', 'О назначении судебного заседания'), ('case_appointment', 'О назначении дела'), ('other', 'Иное постановление')], max_length=50, verbose_name='Тип постановления')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок постановления')),
                ('content', models.TextField(verbose_name='Содержание постановления (HTML)')),
                ('content_raw', models.TextField(verbose_name='Сырое содержимое (Draft.js)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем создано')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='Дата подписания')),
                ('criminal_proceedings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulings', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство')),
            ],
            options={
                'verbose_name': 'Постановление по уголовному делу',
                'verbose_name_plural': 'Постановления по уголовным делам',
                'ordering': ['-created_at'],
            },
        ),
    ]
