# Generated by Django 6.0.1 on 2026-02-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_proceedings', '0002_initial'),
    ]

    operations = [
    ]
