# Generated by Django 6.0.1 on 2026-04-17 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_initial'),
        ('criminal_proceedings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawyercriminal',
            options={'verbose_name': 'Адвокат в уголовном деле', 'verbose_name_plural': 'Адвокаты в уголовных делах'},
        ),
        migrations.RemoveIndex(
            model_name='lawyercriminal',
            name='criminal_pr_petitio_ee9d5e_idx',
        ),
        migrations.AddField(
            model_name='lawyercriminal',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criminal_lawyers', to='business_card.lawyer', verbose_name='Адвокат'),
        ),
        migrations.AddField(
            model_name='lawyercriminal',
            name='sides_case_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criminal_lawyers', to='business_card.sidescase', verbose_name='Роль в деле'),
        ),
        migrations.AddField(
            model_name='petitioncriminal',
            name='petitions_incase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criminal_petitions', to='business_card.petitionsincase', verbose_name='Ходатайство в деле'),
        ),
        migrations.AlterField(
            model_name='lawyercriminal',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_lawyers', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.RemoveField(
            model_name='lawyercriminal',
            name='petitioner_id',
        ),
        migrations.RemoveField(
            model_name='lawyercriminal',
            name='petitioner_type',
        ),
        migrations.RemoveField(
            model_name='lawyercriminal',
            name='petitions_incase',
        ),
    ]
