# Generated by Django 5.2.9 on 2026-01-02 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_proceedings', '0002_remove_criminalproceedings_judge_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferringAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название органа')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Орган, направивший материалы',
                'verbose_name_plural': 'Органы, направившие материалы',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='criminalproceedings',
            name='referring_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='criminal_proceedings.referringauthority', verbose_name='Орган, направивший материалы'),
        ),
    ]
