# Generated by Django 4.2.7 on 2025-12-03 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_proceedings', '0002_criminalruling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminalproceedings',
            name='case_transfer_date',
        ),
        migrations.RemoveField(
            model_name='criminalproceedings',
            name='case_transfer_destination',
        ),
        migrations.RemoveField(
            model_name='criminalproceedings',
            name='first_hearing_date',
        ),
        migrations.RemoveField(
            model_name='criminalproceedings',
            name='hearing_compliance',
        ),
        migrations.RemoveField(
            model_name='criminalproceedings',
            name='hearing_postponed_reason',
        ),
        migrations.RemoveField(
            model_name='criminalproceedings',
            name='hearing_postponed_reason_text',
        ),
        migrations.RemoveField(
            model_name='criminalproceedings',
            name='preliminary_hearing',
        ),
        migrations.RemoveField(
            model_name='criminalproceedings',
            name='preliminary_hearing_date',
        ),
        migrations.RemoveField(
            model_name='criminalproceedings',
            name='preliminary_hearing_result',
        ),
        migrations.RemoveField(
            model_name='criminalproceedings',
            name='resumption_date',
        ),
        migrations.RemoveField(
            model_name='criminalproceedings',
            name='suspension_date',
        ),
        migrations.RemoveField(
            model_name='criminalproceedings',
            name='suspension_reason',
        ),
        migrations.RemoveField(
            model_name='criminalproceedings',
            name='vks_used',
        ),
        migrations.CreateModel(
            name='CriminalCaseMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preliminary_hearing_result', models.CharField(blank=True, choices=[('1', 'о направлении уголовного дела по подсудности'), ('2', 'о возвращении уголовного дела прокурору'), ('3', 'о приостановлении производства по делу'), ('4', 'о прекращении уголовного дела'), ('5', 'о назначении судебного заседания'), ('6', 'о назначении закрытого судебного заседания')], max_length=255, null=True, verbose_name='Результат предварительного слушания')),
                ('first_hearing_date', models.DateField(blank=True, null=True, verbose_name='Дата первого заседания')),
                ('hearing_postponed_reason', models.CharField(blank=True, choices=[('1', 'неявка подсудимого'), ('2', 'неявка защитника'), ('3', 'неявка прокурора'), ('4', 'неявка потерпевшего'), ('5', 'неявка других участников процесса'), ('6', 'неявка свидетелей'), ('7', 'необходимость истребования новых доказательств'), ('8', 'недоставление подсудимого'), ('9', 'назначение экспертизы'), ('10', 'другие основания')], max_length=255, null=True, verbose_name='Причина отложения')),
                ('hearing_postponed_reason_text', models.TextField(blank=True, null=True, verbose_name='Текст причины отложения')),
                ('suspension_date', models.DateField(blank=True, null=True, verbose_name='Дата приостановления производства')),
                ('suspension_reason', models.CharField(blank=True, choices=[('1', 'розыск подсудимого'), ('2', 'психическое заболевание'), ('3', 'другое тяжкое заболевание'), ('4', 'запрос в Конституционный Суд РФ'), ('5', 'невозможность участия обвиняемого в судебном разбирательстве'), ('6', 'невозможность раздельного судебного разбирательства')], max_length=255, null=True, verbose_name='Причина приостановления')),
                ('resumption_date', models.DateField(blank=True, null=True, verbose_name='Дата возобновления производства')),
                ('criminal_proceedings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_movement', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство')),
            ],
            options={
                'verbose_name': 'Движение дела',
                'verbose_name_plural': 'Движения дел',
            },
        ),
    ]
