# Generated by Django 4.2.7 on 2025-09-04 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_initial'),
        ('criminal_proceedings', '0002_defendant_sides_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defendant',
            name='sides_case',
        ),
        migrations.AddField(
            model_name='defendant',
            name='side_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_card.sidescase', verbose_name='Сторона по делу'),
        ),
    ]
