# Generated by Django 5.2.9 on 2026-02-08 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_proceedings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalcasemovement',
            name='criminal_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_movement', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
    ]
