# Generated by Django 5.2.9 on 2026-02-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_proceedings', '0003_alter_criminalcasemovement_criminal_proceedings'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalcasemovement',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время заседания'),
        ),
    ]
