# Generated by Django 6.0.1 on 2026-04-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_initial'),
        ('criminal_proceedings', '0003_alter_lawyercriminal_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petitioncriminal',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='petitioncriminal',
            name='object_id',
        ),
        migrations.AddField(
            model_name='petitioncriminal',
            name='petitioner_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID заявителя'),
        ),
        migrations.AddField(
            model_name='petitioncriminal',
            name='petitioner_type',
            field=models.CharField(blank=True, choices=[('criminal_defendant', 'Обвиняемый'), ('criminal_lawyer', 'Адвокат'), ('criminal_side', 'Сторона по делу')], max_length=30, null=True, verbose_name='Тип заявителя'),
        ),
        migrations.AddIndex(
            model_name='petitioncriminal',
            index=models.Index(fields=['petitioner_type', 'petitioner_id'], name='criminal_pr_petitio_14971e_idx'),
        ),
    ]
