# Generated by Django 4.2.7 on 2025-12-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_proceedings', '0003_remove_criminalproceedings_case_transfer_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalcasemovement',
            name='hearing_compliance',
            field=models.CharField(blank=True, choices=[('1', 'с соблюдением сроков, установленных УПК РФ'), ('2', 'по делам с нарушением сроков')], max_length=1, null=True, verbose_name='Соблюдение сроков'),
        ),
    ]
