# Generated by Django 5.2.9 on 2026-01-21 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0003_lawyer_alter_sidescaseincase_options_and_more'),
        ('criminal_proceedings', '0003_referringauthority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defendant',
            name='side_case',
        ),
        migrations.AddField(
            model_name='defendant',
            name='sides_case_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='criminal_defendants', to='business_card.sidescaseincase', verbose_name='Сторона по делу'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CriminalSidesCase',
        ),
    ]
