# Generated by Django 4.2.7 on 2025-09-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_proceedings', '0003_remove_defendant_sides_case_defendant_side_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_appealed', models.CharField(blank=True, choices=[('1', 'не обжалован'), ('2', 'обжалован осужденным'), ('3', 'обжалован прокурором'), ('4', 'обжалован др. участниками процесса')], max_length=1, null=True, verbose_name='Обжалование приговора')),
                ('appeal_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления апелляции')),
                ('appeal_applicant', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО заявителя апелляции')),
                ('appeal_applicant_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Процессуальное положение заявителя')),
                ('court_instance', models.CharField(blank=True, choices=[('1', 'апелляционной'), ('2', 'кассационной')], max_length=1, null=True, verbose_name='Суд II инстанции')),
                ('court_sent_date', models.DateField(blank=True, null=True, verbose_name='Дата направления в суд II инстанции')),
                ('court_return_date', models.DateField(blank=True, null=True, verbose_name='Дата возвращения из суда II инстанции')),
                ('court_return_reason', models.TextField(blank=True, null=True, verbose_name='Причина возвращения')),
                ('court_resend_date', models.DateField(blank=True, null=True, verbose_name='Дата повторного направления')),
                ('court_consideration_date', models.DateField(blank=True, null=True, verbose_name='Дата рассмотрения во II инстанции')),
                ('consideration_result', models.CharField(blank=True, choices=[('1', 'оставлен без изменения'), ('2', 'отменен с возвращением на новое рассмотрение'), ('3', 'изменен'), ('4', 'вынесен новый приговор (апелляцией)'), ('5', 'отменен с прекращением'), ('6', 'отменено апелляционное постановление'), ('7', 'отменено с возвращением дела прокурору'), ('8', 'иные результаты рассмотрения')], max_length=1, null=True, verbose_name='Результат рассмотрения во II инстанции')),
                ('consideration_changes', models.TextField(blank=True, null=True, verbose_name='Сущность изменений')),
                ('higher_court_receipt_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления из вышестоящего суда')),
                ('sentence_effective_date', models.DateField(blank=True, null=True, verbose_name='Дата вступления в силу')),
                ('sentence_execution_date', models.DateField(blank=True, null=True, verbose_name='Дата обращения к исполнению')),
                ('civil_claim_result', models.CharField(blank=True, choices=[('1', 'удовлетворен полностью'), ('2', 'удовлетворен частично'), ('3', 'оставлен без рассмотрения'), ('4', 'отказано в удовлетворении'), ('5', 'производство прекращено')], max_length=1, null=True, verbose_name='Результат гражданского иска')),
                ('civil_claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма иска')),
                ('state_duty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма госпошлины')),
                ('theft_damage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма ущерба от хищения')),
                ('other_damage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма ущерба от др. преступлений')),
                ('moral_damage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма морального вреда')),
                ('moral_damage_article', models.CharField(blank=True, max_length=50, null=True, verbose_name='Статья УК РФ по моральному вреду')),
                ('copy_sent_to_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Копия направлена 1')),
                ('copy_sent_date_1', models.DateField(blank=True, null=True, verbose_name='Дата направления 1')),
                ('copy_sent_to_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Копия направлена 2')),
                ('copy_sent_date_2', models.DateField(blank=True, null=True, verbose_name='Дата направления 2')),
                ('copy_sent_to_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Копия направлена 3')),
                ('copy_sent_date_3', models.DateField(blank=True, null=True, verbose_name='Дата направления 3')),
                ('joined_with_case', models.CharField(blank=True, max_length=100, null=True, verbose_name='Соединено с делом №')),
                ('separated_to_case', models.CharField(blank=True, max_length=100, null=True, verbose_name='Выделено в дело №')),
                ('expertise_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид экспертизы')),
                ('expertise_sent_date', models.DateField(blank=True, null=True, verbose_name='Дата направления экспертизы')),
                ('expertise_received_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления экспертизы')),
                ('confiscation_article', models.CharField(blank=True, max_length=50, null=True, verbose_name='Статья УК РФ о конфискации')),
                ('court_fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма судебного штрафа')),
                ('court_fine_article', models.CharField(blank=True, max_length=50, null=True, verbose_name='Статья УК РФ о штрафе')),
                ('procedural_coercion', models.TextField(blank=True, null=True, verbose_name='Меры процессуального принуждения')),
                ('procedural_coercion_date', models.DateField(blank=True, null=True, verbose_name='Дата применения мер')),
                ('procedural_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Процессуальные издержки')),
                ('petitions_info', models.TextField(blank=True, null=True, verbose_name='Информация о ходатайствах')),
                ('petitions_withdrawal_date', models.DateField(blank=True, null=True, verbose_name='Дата отзыва ходатайства')),
                ('other_notes', models.TextField(blank=True, null=True, verbose_name='Другие отметки')),
                ('archive_date', models.DateField(blank=True, null=True, verbose_name='Дата сдачи в архив')),
                ('criminal_proceedings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство')),
            ],
            options={
                'verbose_name': 'Решение по уголовному делу',
                'verbose_name_plural': 'Решения по уголовным делам',
            },
        ),
    ]
