# Generated by Django 6.0.1 on 2026-04-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_proceedings', '0004_criminalpersoncard_crimecomposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimecomposition',
            name='article',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Статья УК РФ'),
        ),
    ]
