# Generated by Django 5.2.9 on 2026-02-08 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_initial'),
        ('criminal_proceedings', '0004_criminalcasemovement_meeting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminaldecision',
            name='petitions_info',
        ),
        migrations.RemoveField(
            model_name='criminaldecision',
            name='petitions_withdrawal_date',
        ),
        migrations.CreateModel(
            name='PetitionCriminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal_proceedings_petitions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminal_proceedings.criminalproceedings')),
                ('petitions_criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_lawyer', to='business_card.petitions', verbose_name='Адвокат по делу')),
            ],
            options={
                'verbose_name': 'Ходатайства',
                'verbose_name_plural': 'Ходатайства',
            },
        ),
    ]
