# Generated by Django 5.2.9 on 2026-02-08 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_initial'),
        ('criminal_proceedings', '0005_remove_criminaldecision_petitions_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitioncriminal',
            name='petitions_criminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_petitions', to='business_card.petitions', verbose_name='Ходатайство'),
        ),
    ]
