# Generated by Django 6.0.1 on 2026-04-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_proceedings', '0005_alter_crimecomposition_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminalpersoncard',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='criminalpersoncard',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='criminalpersoncard',
            name='sex',
        ),
        migrations.AlterField(
            model_name='defendant',
            name='citizenship',
            field=models.CharField(blank=True, choices=[('1', 'Российская Федерация'), ('2', 'другие государства СНГ'), ('3', 'иные государства'), ('4', 'без гражданства')], max_length=50, null=True, verbose_name='Гражданство'),
        ),
    ]
