# Generated by Django 4.2.7 on 2025-09-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_proceedings', '0005_remove_criminaldecision_consideration_result_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criminaldecision',
            options={'ordering': ['-appeal_date'], 'verbose_name': 'Решение по уголовному делу', 'verbose_name_plural': 'Решения по уголовным делам'},
        ),
    ]
