# Generated by Django 6.0.1 on 2026-02-09 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_initial'),
        ('criminal_proceedings', '0007_alter_petitioncriminal_petitions_criminal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petitioncriminal',
            options={'verbose_name': 'Ходатайство уголовного дела', 'verbose_name_plural': 'Ходатайства уголовного дела'},
        ),
        migrations.RemoveField(
            model_name='petitioncriminal',
            name='criminal_proceedings_petitions',
        ),
        migrations.AddField(
            model_name='petitioncriminal',
            name='criminal_proceedings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='petitioncriminal',
            name='date_application',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ходатайства'),
        ),
        migrations.AddField(
            model_name='petitioncriminal',
            name='date_decision',
            field=models.DateField(blank=True, null=True, verbose_name='Дата решения по ходатайству'),
        ),
        migrations.AddField(
            model_name='petitioncriminal',
            name='notation',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='примечания'),
        ),
        migrations.RemoveField(
            model_name='petitioncriminal',
            name='petitions_criminal',
        ),
        migrations.AddField(
            model_name='petitioncriminal',
            name='petitions_criminal',
            field=models.ManyToManyField(to='business_card.petitions', verbose_name='ходатайства по делу'),
        ),
    ]
