# Generated by Django 6.0.1 on 2026-02-09 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_initial'),
        ('criminal_proceedings', '0008_alter_petitioncriminal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitioncriminal',
            name='criminal_proceedings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AlterField(
            model_name='petitioncriminal',
            name='petitions_criminal',
            field=models.ManyToManyField(related_name='criminal_petitions', to='business_card.petitions', verbose_name='ходатайства по делу'),
        ),
    ]
