# Generated by Django 6.0.1 on 2026-02-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_proceedings', '0009_alter_petitioncriminal_criminal_proceedings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminaldecision',
            name='archive_date',
        ),
        migrations.RemoveField(
            model_name='criminalproceedings',
            name='case_to_archive_date',
        ),
        migrations.AddField(
            model_name='criminalproceedings',
            name='archive_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания по архивному делу'),
        ),
        migrations.AddField(
            model_name='criminalproceedings',
            name='archived_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сдачи в архив'),
        ),
        migrations.AddField(
            model_name='criminalproceedings',
            name='status',
            field=models.CharField(choices=[('active', 'Активное'), ('completed', 'Рассмотрено'), ('execution', 'На исполнении'), ('archived', 'В архиве')], default='active', max_length=20, verbose_name='Статус дела'),
        ),
    ]
