# Generated by Django 6.0.1 on 2026-02-11 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('criminal_proceedings', '0010_remove_criminaldecision_archive_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitioncriminal',
            name='petitioner_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип стороны'),
        ),
        migrations.AddField(
            model_name='petitioncriminal',
            name='petitioner_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID стороны'),
        ),
        migrations.AddIndex(
            model_name='petitioncriminal',
            index=models.Index(fields=['petitioner_content_type', 'petitioner_object_id'], name='criminal_pr_petitio_e9b0ea_idx'),
        ),
    ]
