# Generated by Django 6.0.1 on 2026-02-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_proceedings', '0011_petitioncriminal_petitioner_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='petitioncriminal',
            name='criminal_pr_petitio_e9b0ea_idx',
        ),
        migrations.RenameField(
            model_name='petitioncriminal',
            old_name='petitioner_content_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='petitioncriminal',
            old_name='petitioner_object_id',
            new_name='object_id',
        ),
    ]
