# Generated by Django 6.0.1 on 2026-02-18 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(blank=True, choices=[('1', 'Иск удовлетворён полностью'), ('2', 'Иск удовлетворён частично'), ('3', 'В иске отказано'), ('4', 'Производство прекращено'), ('5', 'Заявление оставлено без рассмотрения'), ('6', 'Передано по подсудности'), ('7', 'Вынесено судебное решение (не иск)'), ('8', 'Судебный приказ')], max_length=255, null=True, verbose_name='Результат рассмотрения дела')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='Дата вынесения решения')),
                ('decision_motivated_date', models.DateField(blank=True, null=True, verbose_name='Дата составления мотивированного решения')),
                ('decision_effective_date', models.DateField(blank=True, null=True, verbose_name='Дата вступления решения в законную силу')),
                ('appeal_filed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Подана апелляционная жалоба')),
                ('appeal_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления апелляционной жалобы')),
                ('appeal_result', models.CharField(blank=True, choices=[('1', 'Оставлено без изменения'), ('2', 'Изменено'), ('3', 'Отменено с вынесением нового решения'), ('4', 'Отменено с прекращением производства'), ('5', 'Отменено с оставлением заявления без рассмотрения'), ('6', 'Возвращено на новое рассмотрение')], max_length=255, null=True, verbose_name='Результат апелляционного рассмотрения')),
                ('appeal_decision_date', models.DateField(blank=True, null=True, verbose_name='Дата апелляционного определения')),
                ('cassation_filed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Подана кассационная жалоба')),
                ('cassation_result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат кассационного рассмотрения')),
            ],
            options={
                'verbose_name': 'Решение по гражданскому делу',
                'verbose_name_plural': 'Решения по гражданским делам',
                'ordering': ['-decision_date'],
            },
        ),
        migrations.CreateModel(
            name='CivilExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writ_execution_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи исполнительного листа')),
                ('writ_received_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кому выдан исполнительный лист')),
                ('execution_deadline', models.DateField(blank=True, null=True, verbose_name='Срок предъявления к исполнению')),
                ('execution_result', models.CharField(blank=True, choices=[('1', 'Исполнено'), ('2', 'Не исполнено'), ('3', 'Возвращён без исполнения'), ('4', 'Частично исполнено')], max_length=255, null=True, verbose_name='Результат исполнения')),
                ('execution_date', models.DateField(blank=True, null=True, verbose_name='Дата фактического исполнения')),
                ('legal_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Судебные издержки (руб.)')),
                ('legal_costs_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Присуждённые издержки (руб.)')),
            ],
            options={
                'verbose_name': 'Исполнение по гражданскому делу',
                'verbose_name_plural': 'Исполнения по гражданским делам',
                'ordering': ['-writ_execution_date'],
            },
        ),
        migrations.CreateModel(
            name='CivilProceedings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number_civil', models.CharField(max_length=100, unique=True, verbose_name='Номер гражданского дела')),
                ('incoming_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления дела в суд')),
                ('incoming_from', models.CharField(blank=True, max_length=255, null=True, verbose_name='Откуда поступило дело')),
                ('judge_acceptance_date', models.DateField(blank=True, null=True, verbose_name='Дата принятия дела судьёй')),
                ('judge_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код судьи')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория дела')),
                ('case_type', models.CharField(blank=True, choices=[('1', 'Исковое производство'), ('2', 'Приказное производство'), ('3', 'Особое производство'), ('4', 'Упрощенное производство')], max_length=255, null=True, verbose_name='Вид производства')),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена иска (руб.)')),
                ('claim_subject', models.TextField(blank=True, null=True, verbose_name='Предмет иска')),
                ('claim_basis', models.TextField(blank=True, null=True, verbose_name='Основание иска')),
                ('claim_date', models.DateField(blank=True, null=True, verbose_name='Дата предъявления иска')),
                ('state_duty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Государственная пошлина (руб.)')),
                ('state_duty_paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Госпошлина уплачена')),
                ('preliminary_hearing_date', models.DateField(blank=True, null=True, verbose_name='Дата предварительного судебного заседания')),
                ('preliminary_hearing_result', models.CharField(blank=True, choices=[('1', 'Назначено к судебному разбирательству'), ('2', 'Отложено'), ('3', 'Прекращено производство'), ('4', 'Оставлено без рассмотрения'), ('5', 'Передано по подсудности')], max_length=255, null=True, verbose_name='Результат предварительного заседания')),
                ('first_hearing_date', models.DateField(blank=True, null=True, verbose_name='Дата первого судебного заседания')),
                ('hearing_date', models.DateField(blank=True, null=True, verbose_name='Дата рассмотрения (последнего заседания)')),
                ('hearing_compliance', models.CharField(blank=True, choices=[('1', 'С соблюдением сроков, установленных ГПК РФ'), ('2', 'С нарушением сроков')], max_length=1, null=True, verbose_name='Соблюдение сроков рассмотрения')),
                ('hearing_postponed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Дело откладывалось')),
                ('postponement_reason', models.TextField(blank=True, null=True, verbose_name='Причины отложения')),
                ('case_suspended', models.BooleanField(blank=True, default=False, null=True, verbose_name='Производство по делу приостанавливалось')),
                ('suspension_reason', models.CharField(blank=True, choices=[('1', 'Смерть гражданина, реорганизация юрлица'), ('2', 'Признание стороны недееспособной'), ('3', 'Пребывание стороны в лечебном учреждении'), ('4', 'Розыск ответчика'), ('5', 'Назначение экспертизы'), ('6', 'Иное')], max_length=255, null=True, verbose_name='Основание приостановления')),
                ('suspension_date', models.DateField(blank=True, null=True, verbose_name='Дата приостановления')),
                ('resumption_date', models.DateField(blank=True, null=True, verbose_name='Дата возобновления производства')),
                ('special_notes', models.TextField(blank=True, null=True, verbose_name='Особые отметки')),
                ('status', models.CharField(choices=[('active', 'Активное'), ('completed', 'Рассмотрено'), ('execution', 'На исполнении'), ('archived', 'В архиве')], default='active', max_length=20, verbose_name='Статус дела')),
                ('archived_date', models.DateField(blank=True, null=True, verbose_name='Дата сдачи в архив')),
                ('archive_notes', models.TextField(blank=True, null=True, verbose_name='Примечания по архивному делу')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Гражданское производство',
                'verbose_name_plural': 'Гражданские производства',
                'ordering': ['-incoming_date'],
            },
        ),
        migrations.CreateModel(
            name='CivilSidesCaseInCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Сторона гражданского дела',
                'verbose_name_plural': 'Стороны гражданского дела',
            },
        ),
        migrations.CreateModel(
            name='ReferringAuthorityCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название органа')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Орган, направивший материалы',
                'verbose_name_plural': 'Органы, направившие материалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CivilCaseMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_movements', to='business_card.businessmovement', verbose_name='Движение дела (из business_card)')),
            ],
            options={
                'verbose_name': 'Движение дела (гражданское)',
                'verbose_name_plural': 'Движения дела (гражданские)',
                'ordering': ['-business_movement__date_meeting', '-business_movement__meeting_time'],
            },
        ),
        migrations.CreateModel(
            name='CivilLawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_lawyers', to='business_card.lawyer', verbose_name='Адвокат (данные из business_card)')),
                ('sides_case_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_lawyers', to='business_card.sidescase', verbose_name='Представитель какой стороны')),
            ],
            options={
                'verbose_name': 'Адвокат в гражданском деле',
                'verbose_name_plural': 'Адвокаты в гражданских делах',
            },
        ),
        migrations.CreateModel(
            name='CivilPetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petitioner_type', models.CharField(blank=True, choices=[('civil_sides', 'Сторона по делу'), ('civil_lawyer', 'Адвокат')], max_length=20, null=True, verbose_name='Тип заявителя')),
                ('petitioner_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID заявителя')),
                ('petitions_incase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_petitions', to='business_card.petitionsincase', verbose_name='Ходатайство')),
            ],
            options={
                'verbose_name': 'Ходатайство в гражданском деле',
                'verbose_name_plural': 'Ходатайства в гражданских делах',
            },
        ),
    ]
