# Generated by Django 6.0.1 on 2026-02-18 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_card', '0002_initial'),
        ('case_registry', '0003_initial'),
        ('civil_proceedings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='civilproceedings',
            name='presiding_judge',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'judge'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Судья (председательствующий)'),
        ),
        migrations.AddField(
            model_name='civilproceedings',
            name='registered_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civil_proceedings_link', to='case_registry.registeredcase', verbose_name='Зарегистрированное дело'),
        ),
        migrations.AddField(
            model_name='civilpetition',
            name='civil_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_petitions', to='civil_proceedings.civilproceedings', verbose_name='Гражданское производство'),
        ),
        migrations.AddField(
            model_name='civillawyer',
            name='civil_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_lawyers', to='civil_proceedings.civilproceedings', verbose_name='Гражданское производство'),
        ),
        migrations.AddField(
            model_name='civilexecution',
            name='civil_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_executions', to='civil_proceedings.civilproceedings', verbose_name='Гражданское производство'),
        ),
        migrations.AddField(
            model_name='civildecision',
            name='civil_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_decisions', to='civil_proceedings.civilproceedings', verbose_name='Гражданское производство'),
        ),
        migrations.AddField(
            model_name='civilcasemovement',
            name='civil_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_movements', to='civil_proceedings.civilproceedings', verbose_name='Гражданское производство'),
        ),
        migrations.AddField(
            model_name='civilsidescaseincase',
            name='civil_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_sides', to='civil_proceedings.civilproceedings', verbose_name='Гражданское производство'),
        ),
        migrations.AddField(
            model_name='civilsidescaseincase',
            name='sides_case_incase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_sides', to='business_card.sidescaseincase', verbose_name='Данные стороны (ФИО/наименование, контакты)'),
        ),
        migrations.AddField(
            model_name='civilsidescaseincase',
            name='sides_case_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_sides', to='business_card.sidescase', verbose_name='Роль стороны (истец, ответчик, третье лицо и т.д.)'),
        ),
        migrations.AddField(
            model_name='civilproceedings',
            name='referring_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='civil_proceedings.referringauthoritycivil', verbose_name='Орган, направивший дело'),
        ),
        migrations.AddIndex(
            model_name='civilpetition',
            index=models.Index(fields=['petitioner_type', 'petitioner_id'], name='civil_proce_petitio_fa9b5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='civilsidescaseincase',
            unique_together={('civil_proceedings', 'sides_case_incase', 'sides_case_role')},
        ),
    ]
