# Generated by Django 6.0.1 on 2026-02-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civil_proceedings', '0004_alter_civilproceedings_presiding_judge'),
    ]

    operations = [
    ]
