# Generated by Django 6.0.1 on 2026-03-02 12:15

import django.core.validators
import legal_documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название документа')),
                ('document_type', models.CharField(choices=[('plenum', 'Постановление Пленума ВС РФ'), ('review', 'Обзор практики ВС РФ'), ('reference', 'Справочные материалы')], max_length=20, verbose_name='Тип документа')),
                ('category', models.CharField(choices=[('criminal', 'Уголовные'), ('civil', 'Гражданские'), ('administrative', 'Административные (КАС)'), ('arbitration', 'Арбитражные'), ('coap', 'КОАП'), ('military', 'Военные'), ('general', 'Общие вопросы')], max_length=20, verbose_name='Категория')),
                ('file_word', models.FileField(blank=True, null=True, upload_to=legal_documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])], verbose_name='Файл Word')),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to=legal_documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Файл PDF')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Номер документа')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('articles', models.TextField(blank=True, help_text='Статьи через запятую (например: УК 105, ГК 309, КОАП 12.8)', verbose_name='Статьи')),
                ('keywords', models.TextField(blank=True, help_text='Ключевые слова через запятую', verbose_name='Ключевые слова')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Источник')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Правовой документ',
                'verbose_name_plural': 'Правовые документы',
                'ordering': ['-document_date', '-uploaded_at'],
            },
        ),
    ]
