# Generated by Django 6.0.1 on 2026-03-02 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal_documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил пользователь'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['document_type', 'category'], name='legal_docum_documen_19fce0_idx'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['document_date'], name='legal_docum_documen_737b27_idx'),
        ),
    ]
