# Generated by Django 6.0.1 on 2026-04-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeCaseMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Движение дела (административное)',
                'verbose_name_plural': 'Движения дела (административные)',
                'ordering': ['-business_movement__date_meeting', '-business_movement__meeting_time'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(blank=True, choices=[('1', 'Назначено административное наказание'), ('2', 'Прекращено производство по делу'), ('3', 'Возвращено для устранения недостатков'), ('4', 'Передано по подведомственности'), ('5', 'Вынесено предупреждение')], max_length=255, null=True, verbose_name='Результат рассмотрения дела')),
                ('punishment_type', models.CharField(blank=True, choices=[('1', 'Предупреждение'), ('2', 'Административный штраф'), ('3', 'Конфискация орудия или предмета'), ('4', 'Лишение специального права'), ('5', 'Административный арест'), ('6', 'Дисквалификация'), ('7', 'Административное приостановление деятельности'), ('8', 'Обязательные работы'), ('9', 'Административное выдворение')], max_length=255, null=True, verbose_name='Вид наказания')),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма штрафа (руб.)')),
                ('deprivation_period', models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок лишения специального права')),
                ('arrest_period', models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок административного ареста')),
                ('suspension_period', models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок приостановления деятельности')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='Дата вынесения постановления')),
                ('decision_motivated_date', models.DateField(blank=True, null=True, verbose_name='Дата составления мотивированного постановления')),
                ('decision_effective_date', models.DateField(blank=True, null=True, verbose_name='Дата вступления постановления в законную силу')),
                ('complaint_filed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Подана жалоба')),
                ('complaint_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления жалобы')),
                ('complaint_result', models.CharField(blank=True, choices=[('1', 'Постановление оставлено без изменения'), ('2', 'Постановление изменено'), ('3', 'Постановление отменено, дело прекращено'), ('4', 'Постановление отменено, дело возвращено на новое рассмотрение'), ('5', 'Постановление отменено, дело направлено по подведомственности')], max_length=255, null=True, verbose_name='Результат рассмотрения жалобы')),
                ('complaint_decision_date', models.DateField(blank=True, null=True, verbose_name='Дата решения по жалобе')),
            ],
            options={
                'verbose_name': 'Постановление по делу об АП',
                'verbose_name_plural': 'Постановления по делам об АП',
                'ordering': ['-decision_date'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_document_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи исполнительного документа')),
                ('execution_document_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер исполнительного документа')),
                ('execution_document_received_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кому направлен исполнительный документ')),
                ('fine_paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Штраф уплачен')),
                ('fine_paid_date', models.DateField(blank=True, null=True, verbose_name='Дата уплаты штрафа')),
                ('fine_paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Уплаченная сумма (руб.)')),
                ('confiscation_executed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Конфискация исполнена')),
                ('confiscation_executed_date', models.DateField(blank=True, null=True, verbose_name='Дата исполнения конфискации')),
                ('deprivation_executed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Лишение спецправа исполнено')),
                ('deprivation_start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала срока лишения')),
                ('deprivation_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания срока лишения')),
                ('arrest_executed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Административный арест исполнен')),
                ('arrest_period_served', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отбытый срок ареста')),
                ('suspension_executed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Приостановление деятельности исполнено')),
                ('suspension_start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала приостановления')),
                ('suspension_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания приостановления')),
                ('execution_result', models.CharField(blank=True, choices=[('1', 'Исполнено'), ('2', 'Не исполнено'), ('3', 'Возвращено без исполнения'), ('4', 'Частично исполнено')], max_length=255, null=True, verbose_name='Результат исполнения')),
                ('execution_date', models.DateField(blank=True, null=True, verbose_name='Дата фактического исполнения')),
                ('bailiff_department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отдел судебных приставов')),
                ('bailiff_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Судебный пристав-исполнитель')),
                ('enforcement_proceedings_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер исполнительного производства')),
            ],
            options={
                'verbose_name': 'Исполнение по делу об АП',
                'verbose_name_plural': 'Исполнения по делам об АП',
                'ordering': ['-execution_document_date'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativeLawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Защитник в деле об АП',
                'verbose_name_plural': 'Защитники в делах об АП',
            },
        ),
        migrations.CreateModel(
            name='AdministrativePetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petitioner_type', models.CharField(blank=True, choices=[('admin_sides', 'Сторона по делу'), ('admin_lawyer', 'Защитник')], max_length=20, null=True, verbose_name='Тип заявителя')),
                ('petitioner_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID заявителя')),
            ],
            options={
                'verbose_name': 'Ходатайство в деле об АП',
                'verbose_name_plural': 'Ходатайства в делах об АП',
            },
        ),
        migrations.CreateModel(
            name='AdministrativeProceedings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number_admin', models.CharField(max_length=100, unique=True, verbose_name='Номер дела об АП')),
                ('incoming_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления дела в суд')),
                ('incoming_from', models.CharField(blank=True, max_length=255, null=True, verbose_name='Откуда поступило дело')),
                ('protocol_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер протокола об АП')),
                ('protocol_date', models.DateField(blank=True, null=True, verbose_name='Дата составления протокола')),
                ('judge_acceptance_date', models.DateField(blank=True, null=True, verbose_name='Дата принятия дела судьёй')),
                ('judge_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код судьи')),
                ('article_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Статья КоАП РФ')),
                ('article_part', models.CharField(blank=True, max_length=50, null=True, verbose_name='Часть статьи')),
                ('offense_description', models.TextField(blank=True, null=True, verbose_name='Описание правонарушения')),
                ('offense_date', models.DateField(blank=True, null=True, verbose_name='Дата совершения правонарушения')),
                ('offense_time', models.TimeField(blank=True, null=True, verbose_name='Время совершения правонарушения')),
                ('offense_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место совершения правонарушения')),
                ('consideration_type', models.CharField(blank=True, choices=[('1', 'Единолично судьёй'), ('2', 'Коллегиально'), ('3', 'С участием прокурора')], max_length=255, null=True, verbose_name='Вид рассмотрения')),
                ('hearing_date', models.DateField(blank=True, null=True, verbose_name='Дата рассмотрения дела')),
                ('hearing_time', models.TimeField(blank=True, null=True, verbose_name='Время рассмотрения дела')),
                ('hearing_postponed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Рассмотрение откладывалось')),
                ('postponement_reason', models.TextField(blank=True, null=True, verbose_name='Причины отложения')),
                ('postponement_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество отложений')),
                ('case_suspended', models.BooleanField(blank=True, default=False, null=True, verbose_name='Производство по делу приостанавливалось')),
                ('suspension_reason', models.CharField(blank=True, choices=[('1', 'Розыск лица, в отношении которого ведётся производство'), ('2', 'Назначение экспертизы'), ('3', 'Направление запроса в Конституционный Суд РФ'), ('4', 'Иное')], max_length=255, null=True, verbose_name='Основание приостановления')),
                ('suspension_date', models.DateField(blank=True, null=True, verbose_name='Дата приостановления')),
                ('resumption_date', models.DateField(blank=True, null=True, verbose_name='Дата возобновления производства')),
                ('special_notes', models.TextField(blank=True, null=True, verbose_name='Особые отметки')),
                ('status', models.CharField(choices=[('active', 'Активное'), ('completed', 'Рассмотрено'), ('execution', 'На исполнении'), ('archived', 'В архиве')], default='active', max_length=20, verbose_name='Статус дела')),
                ('archived_date', models.DateField(blank=True, null=True, verbose_name='Дата сдачи в архив')),
                ('archive_notes', models.TextField(blank=True, null=True, verbose_name='Примечания по архивному делу')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Дело об административном правонарушении',
                'verbose_name_plural': 'Дела об административных правонарушениях',
                'ordering': ['-incoming_date'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativeSidesCaseInCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Сторона дела об АП',
                'verbose_name_plural': 'Стороны дела об АП',
            },
        ),
        migrations.CreateModel(
            name='ReferringAuthorityAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название органа')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Орган, составивший протокол',
                'verbose_name_plural': 'Органы, составившие протокол',
                'ordering': ['name'],
            },
        ),
    ]
