# Generated by Django 6.0.1 on 2026-03-02 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrative_code', '0002_initial'),
        ('business_card', '0001_initial'),
        ('case_registry', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeproceedings',
            name='presiding_judge',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'judge'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Судья (председательствующий)'),
        ),
        migrations.AddField(
            model_name='administrativeproceedings',
            name='registered_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_proceedings_link', to='case_registry.registeredcase', verbose_name='Зарегистрированное дело'),
        ),
        migrations.AddField(
            model_name='administrativepetition',
            name='administrative_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_petitions', to='administrative_code.administrativeproceedings', verbose_name='Дело об АП'),
        ),
        migrations.AddField(
            model_name='administrativelawyer',
            name='administrative_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_lawyers', to='administrative_code.administrativeproceedings', verbose_name='Дело об АП'),
        ),
        migrations.AddField(
            model_name='administrativeexecution',
            name='administrative_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_executions', to='administrative_code.administrativeproceedings', verbose_name='Дело об АП'),
        ),
        migrations.AddField(
            model_name='administrativedecision',
            name='administrative_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_decisions', to='administrative_code.administrativeproceedings', verbose_name='Дело об АП'),
        ),
        migrations.AddField(
            model_name='administrativecasemovement',
            name='administrative_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_movements', to='administrative_code.administrativeproceedings', verbose_name='Дело об АП'),
        ),
        migrations.AddField(
            model_name='administrativesidescaseincase',
            name='administrative_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_sides', to='administrative_code.administrativeproceedings', verbose_name='Дело об АП'),
        ),
        migrations.AddField(
            model_name='administrativesidescaseincase',
            name='sides_case_incase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_sides', to='business_card.sidescaseincase', verbose_name='Данные стороны (ФИО/наименование, контакты)'),
        ),
        migrations.AddField(
            model_name='administrativesidescaseincase',
            name='sides_case_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_sides', to='business_card.sidescase', verbose_name='Роль стороны (лицо, потерпевший, защитник и т.д.)'),
        ),
        migrations.AddField(
            model_name='administrativeproceedings',
            name='referring_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrative_code.referringauthorityadmin', verbose_name='Орган, составивший протокол'),
        ),
        migrations.AddIndex(
            model_name='administrativepetition',
            index=models.Index(fields=['petitioner_type', 'petitioner_id'], name='administrat_petitio_0249b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='administrativesidescaseincase',
            unique_together={('administrative_proceedings', 'sides_case_incase', 'sides_case_role')},
        ),
    ]
