# Generated by Django 6.0.1 on 2026-04-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_code', '0003_initial'),
        ('business_card', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория дела (КоАП)',
                'verbose_name_plural': 'Категории дел (КоАП)',
            },
        ),
        migrations.CreateModel(
            name='CaseOrderAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Порядок поступления дела (КоАП)',
                'verbose_name_plural': 'Порядок поступления дел (КоАП)',
            },
        ),
        migrations.CreateModel(
            name='ExecutionStageAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Стадия исполнения (КоАП)',
                'verbose_name_plural': 'Стадии исполнения (КоАП)',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PostponementReasonAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Причина отложения (КоАП)',
                'verbose_name_plural': 'Причины отложения (КоАП)',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SuspensionReasonAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Причина приостановления (КоАП)',
                'verbose_name_plural': 'Причины приостановления (КоАП)',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='administrativedecision',
            name='complaint_date',
        ),
        migrations.RemoveField(
            model_name='administrativedecision',
            name='complaint_decision_date',
        ),
        migrations.RemoveField(
            model_name='administrativedecision',
            name='complaint_filed',
        ),
        migrations.RemoveField(
            model_name='administrativedecision',
            name='complaint_result',
        ),
        migrations.AddField(
            model_name='administrativedecision',
            name='disqualification_period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок дисквалификации'),
        ),
        migrations.AddField(
            model_name='administrativedecision',
            name='immediate_execution',
            field=models.BooleanField(default=False, verbose_name='Постановление обращено к немедленному исполнению'),
        ),
        migrations.AddField(
            model_name='administrativedecision',
            name='is_auto_fixed_5000',
            field=models.BooleanField(default=False, verbose_name='Штраф 5000 руб. при автофиксации (ч. 3.1 ст. 4.1 КоАП РФ)'),
        ),
        migrations.AddField(
            model_name='administrativedecision',
            name='is_below_lowest_limit',
            field=models.BooleanField(default=False, verbose_name='Наказание назначено ниже низшего предела (ст. 4.1 КоАП РФ)'),
        ),
        migrations.AddField(
            model_name='administrativedecision',
            name='mandatory_work_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Обязательные работы (часов)'),
        ),
        migrations.AddField(
            model_name='administrativeproceedings',
            name='postponement_reason_text',
            field=models.TextField(blank=True, null=True, verbose_name='Иная причина отложения (текстом)'),
        ),
        migrations.AddField(
            model_name='administrativeproceedings',
            name='suspension_reason_text',
            field=models.TextField(blank=True, null=True, verbose_name='Иное основание приостановления (текстом)'),
        ),
        migrations.AddField(
            model_name='administrativeproceedings',
            name='term_compliance',
            field=models.CharField(blank=True, choices=[('1', 'С соблюдением'), ('2', 'С нарушением')], max_length=10, null=True, verbose_name='Соблюдение сроков рассмотрения'),
        ),
        migrations.AlterField(
            model_name='administrativeexecution',
            name='execution_result',
            field=models.CharField(blank=True, choices=[('1', 'Исполнено'), ('2', 'Не исполнено'), ('3', 'Возвращено без исполнения'), ('4', 'Частично исполнено'), ('5', 'Направлено по принадлежности')], max_length=255, null=True, verbose_name='Результат исполнения'),
        ),
        migrations.CreateModel(
            name='AdministrativeAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_filed', models.BooleanField(default=False, verbose_name='Подана жалоба (протест)')),
                ('complaint_type', models.CharField(blank=True, choices=[('complaint', 'Жалоба'), ('protest', 'Протест прокурора')], max_length=20, null=True, verbose_name='Тип обжалования')),
                ('complaint_filed_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем подана жалоба (протест)')),
                ('complaint_filed_date', models.DateField(blank=True, null=True, verbose_name='Дата подачи жалобы (протеста)')),
                ('complaint_received_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления в суд')),
                ('case_sent_to_higher_court_date', models.DateField(blank=True, null=True, verbose_name='Дата направления дела в вышестоящий суд')),
                ('higher_court_case_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер дела в вышестоящем суде')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('review_result', models.CharField(blank=True, choices=[('1', 'Оставлено без изменения'), ('2', 'Отменено'), ('3', 'Изменено'), ('4', 'Производство прекращено'), ('5', 'Вынесено новое решение')], max_length=10, null=True, verbose_name='Результат рассмотрения жалобы (протеста)')),
                ('result_description', models.TextField(blank=True, null=True, verbose_name='Описание результата (суть изменений)')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='Дата вынесения апелляционного определения')),
                ('decision_effective_date', models.DateField(blank=True, null=True, verbose_name='Дата вступления в силу')),
                ('administrative_proceedings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='administrative_code.administrativeproceedings', verbose_name='Дело об АП')),
            ],
            options={
                'verbose_name': 'Апелляционное обжалование (КоАП)',
                'verbose_name_plural': 'Апелляционные обжалования (КоАП)',
            },
        ),
        migrations.CreateModel(
            name='AdministrativeCassation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cassation_filed', models.BooleanField(default=False, verbose_name='Подана кассационная жалоба (протест)')),
                ('cassation_type', models.CharField(blank=True, choices=[('complaint', 'Жалоба'), ('protest', 'Протест прокурора')], max_length=20, null=True, verbose_name='Тип кассационного обжалования')),
                ('cassation_filed_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем подана кассационная жалоба (протест)')),
                ('cassation_filed_date', models.DateField(blank=True, null=True, verbose_name='Дата подачи кассационной жалобы (протеста)')),
                ('cassation_received_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления в суд')),
                ('cassation_review_date', models.DateField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('cassation_result', models.CharField(blank=True, choices=[('1', 'Оставлено без изменения'), ('2', 'Отменено'), ('3', 'Изменено'), ('4', 'Производство прекращено')], max_length=10, null=True, verbose_name='Результат рассмотрения кассационной жалобы (протеста)')),
                ('cassation_result_description', models.TextField(blank=True, null=True, verbose_name='Описание результата (суть изменений)')),
                ('cassation_decision_date', models.DateField(blank=True, null=True, verbose_name='Дата вынесения кассационного определения')),
                ('administrative_proceedings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cassation', to='administrative_code.administrativeproceedings', verbose_name='Дело об АП')),
            ],
            options={
                'verbose_name': 'Кассационное обжалование (КоАП)',
                'verbose_name_plural': 'Кассационные обжалования (КоАП)',
            },
        ),
        migrations.AddField(
            model_name='administrativeproceedings',
            name='case_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrative_code.administrativecategory', verbose_name='Категория дела'),
        ),
        migrations.CreateModel(
            name='AdministrativeSecurityMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_type', models.CharField(choices=[('delivery', 'Доставление'), ('detention', 'Административное задержание'), ('drive', 'Привод'), ('personal_search', 'Личный досмотр'), ('search_of_items', 'Досмотр вещей'), ('vehicle_search', 'Досмотр транспортного средства'), ('examination', 'Осмотр помещений'), ('removal_from_driving', 'Отстранение от управления ТС'), ('alcohol_examination', 'Освидетельствование на состояние алкогольного опьянения'), ('medical_examination', 'Медицинское освидетельствование на состояние опьянения'), ('seizure_of_items', 'Изъятие вещей и документов'), ('detention_of_vehicle', 'Задержание транспортного средства'), ('arrest_of_goods', 'Арест товаров, транспортных средств и иных вещей'), ('pledge_for_vessel', 'Залог за арестованное судно'), ('temporary_ban', 'Временный запрет деятельности'), ('arrest_of_property', 'Арест имущества (ст. 19.28 КоАП РФ)'), ('placement_in_special_institution', 'Помещение в специальное учреждение (иностранных граждан)')], max_length=50, verbose_name='Вид меры обеспечения')),
                ('applied_date', models.DateField(blank=True, null=True, verbose_name='Дата применения')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма (для залога, ареста имущества и т.д.)')),
                ('period', models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок (для помещения в спецучреждение)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('administrative_proceedings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_measures', to='administrative_code.administrativeproceedings', verbose_name='Дело об АП')),
            ],
            options={
                'verbose_name': 'Мера обеспечения производства (КоАП)',
                'verbose_name_plural': 'Меры обеспечения производства (КоАП)',
            },
        ),
        migrations.AddField(
            model_name='administrativeproceedings',
            name='case_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrative_code.caseorderadmin', verbose_name='Порядок поступления дела'),
        ),
        migrations.AddField(
            model_name='administrativeexecution',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrative_code.executionstageadmin', verbose_name='Стадия исполнения'),
        ),
        migrations.AlterField(
            model_name='administrativeproceedings',
            name='postponement_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrative_code.postponementreasonadmin', verbose_name='Причина отложения'),
        ),
        migrations.AlterField(
            model_name='administrativeproceedings',
            name='suspension_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrative_code.suspensionreasonadmin', verbose_name='Основание приостановления'),
        ),
        migrations.CreateModel(
            name='AdministrativeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('legal_entity', 'Юридическое лицо'), ('official', 'Должностное лицо'), ('entrepreneur', 'Лицо, осуществляющее предпринимательскую деятельность'), ('military', 'Военнослужащий'), ('foreign', 'Иностранный гражданин/лицо без гражданства'), ('federal_civil_servant', 'Федеральный государственный гражданский служащий'), ('regional_civil_servant', 'Государственный гражданский служащий субъекта РФ'), ('municipal_servant', 'Служащий органа местного самоуправления'), ('other_physical', 'Иное физическое лицо')], max_length=50, verbose_name='Тип субъекта')),
                ('administrative_proceedings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='administrative_code.administrativeproceedings', verbose_name='Дело об АП')),
                ('sides_case_incase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_card.sidescaseincase', verbose_name='Сторона (из business_card)')),
            ],
            options={
                'verbose_name': 'Субъект административного правонарушения',
                'verbose_name_plural': 'Субъекты административных правонарушений',
                'unique_together': {('administrative_proceedings', 'subject_type')},
            },
        ),
    ]
