# Generated by Django 6.0.1 on 2026-04-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифицирован'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_series',
            field=models.CharField(blank=True, max_length=10, verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата верификации'),
        ),
        migrations.AddField(
            model_name='user',
            name='vk_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='VK ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='yandex_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Яндекс ID'),
        ),
    ]
