# Generated by Django 6.0.1 on 2026-04-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birth_date_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Пол'),
        ),
    ]
