# Generated by Django 6.0.1 on 2026-04-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Кэш статистики',
                'verbose_name_plural': 'Кэши статистики',
            },
        ),
    ]
