# Generated by Django 6.0.1 on 2026-04-23 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenCaseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID дела')),
                ('access_type', models.CharField(choices=[('view', 'Только просмотр'), ('petition', 'Подача ходатайств'), ('documents', 'Досылка документов'), ('full', 'Полный доступ (просмотр + ходатайства + документы)')], default='view', max_length=20, verbose_name='Тип доступа')),
                ('role_in_case', models.CharField(blank=True, max_length=100, verbose_name='Роль в деле')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата предоставления доступа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступ активен')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Гражданин')),
                ('content_type', models.ForeignKey(limit_choices_to={'app_label__in': ['criminal_proceedings', 'civil_proceedings', 'administrative_proceedings', 'administrative_code'], 'model__in': ['criminalproceedings', 'civilproceedings', 'administrativeproceedings', 'kasproceedings']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип дела')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Кто предоставил доступ')),
            ],
            options={
                'verbose_name': 'Доступ гражданина к делу',
                'verbose_name_plural': 'Доступы граждан к делам',
                'unique_together': {('citizen', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='CitizenDocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='citizen_documents/%Y/%m/', verbose_name='Файл документа')),
                ('file_name', models.CharField(blank=True, max_length=500, verbose_name='Исходное имя файла')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус')),
                ('court_comment', models.TextField(blank=True, verbose_name='Комментарий суда')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('case_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='citizen_access.citizencaseaccess', verbose_name='Доступ к делу')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_documents', to=settings.AUTH_USER_MODEL, verbose_name='Гражданин')),
            ],
            options={
                'verbose_name': 'Документ гражданина',
                'verbose_name_plural': 'Документы граждан',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CitizenPetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок ходатайства')),
                ('content', models.TextField(verbose_name='Текст ходатайства')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Прикрепленные файлы')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подано'), ('accepted', 'Принято к рассмотрению'), ('rejected', 'Отклонено'), ('resolved', 'Рассмотрено')], default='draft', max_length=20, verbose_name='Статус')),
                ('court_response', models.TextField(blank=True, verbose_name='Ответ суда')),
                ('court_response_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подачи')),
                ('case_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to='citizen_access.citizencaseaccess', verbose_name='Доступ к делу')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_petitions', to=settings.AUTH_USER_MODEL, verbose_name='Гражданин')),
            ],
            options={
                'verbose_name': 'Ходатайство гражданина',
                'verbose_name_plural': 'Ходатайства граждан',
                'ordering': ['-created_at'],
            },
        ),
    ]
