# Generated by Django 4.2.7 on 2025-12-09 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('criminal_proceedings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(choices=[('pre_trial_preparation', 'Подготовка к судебному заседанию (30 дней)'), ('trial_start', 'Начало судебного разбирательства'), ('decision_making', 'Вынесение решения')], max_length=50)),
                ('deadline_date', models.DateField(verbose_name='Крайний срок')),
                ('days_remaining', models.IntegerField(verbose_name='Осталось дней')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Предупреждение о сроке',
                'verbose_name_plural': 'Предупреждения о сроках',
            },
        ),
        migrations.CreateModel(
            name='JurisdictionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type_actual', models.CharField(choices=[('magistrate', 'Мировой судья (до 3 лет)'), ('district', 'Районный суд (свыше 3 лет)'), ('subject', 'Суд субъекта')], max_length=20, verbose_name='Фактический тип дела')),
                ('case_type_required', models.CharField(choices=[('magistrate', 'Мировой судья (до 3 лет)'), ('district', 'Районный суд (свыше 3 лет)'), ('subject', 'Суд субъекта')], max_length=20, verbose_name='Требуемый тип дела')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Подсудность верна')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Проверка подсудности',
                'verbose_name_plural': 'Проверки подсудности',
            },
        ),
        migrations.CreateModel(
            name='LegalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(choices=[('plenum', 'Постановление Пленума'), ('vs_decision', 'Решение ВС РФ'), ('excerpt', 'Выдержка практики'), ('other', 'Другое')], default='other', max_length=32)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='legal_references/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название правила')),
                ('rule_type', models.CharField(choices=[('jurisdiction_check', 'Проверка подсудности'), ('deadline_warning', 'Предупреждение о сроке'), ('required_action', 'Обязательное действие'), ('status_change', 'Изменение статуса')], max_length=50)),
                ('target_model', models.CharField(max_length=100, verbose_name='Целевая модель')),
                ('condition', models.JSONField(help_text='JSON с условиями', verbose_name='Условие срабатывания')),
                ('days_before', models.IntegerField(default=0, verbose_name='Дней до события')),
                ('title_template', models.CharField(max_length=500, verbose_name='Шаблон заголовка')),
                ('message_template', models.TextField(verbose_name='Шаблон сообщения')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=512, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=20)),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('criminal_proceeding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное дело')),
                ('jurisdiction_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.jurisdictioncheck', verbose_name='Проверка подсудности')),
                ('legal_references', models.ManyToManyField(blank=True, to='notifications.legalreference', verbose_name='Правовые ссылки')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
