# Generated by Django 4.2.7 on 2025-10-13 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
        ('criminal_proceedings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='jurisdictioncheck',
            name='criminal_proceeding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное дело'),
        ),
        migrations.AddField(
            model_name='jurisdictioncheck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Проверивший судья'),
        ),
        migrations.AddField(
            model_name='deadlinewarning',
            name='criminal_proceeding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное дело'),
        ),
    ]
