# Generated by Django 6.0.1 on 2026-04-22 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrative_code', '0003_initial'),
        ('administrative_proceedings', '0003_initial'),
        ('case_registry', '0003_initial'),
        ('civil_proceedings', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('criminal_proceedings', '0002_initial'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisdictioncheck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Проверивший судья'),
        ),
        migrations.AddField(
            model_name='notification',
            name='admin_proceeding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrative_code.administrativeproceedings', verbose_name='Административное дело (КоАП)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='civil_proceeding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='civil_proceedings.civilproceedings', verbose_name='Гражданское дело'),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='correspondence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_registry.correspondence', verbose_name='Связанная корреспонденция'),
        ),
        migrations.AddField(
            model_name='notification',
            name='criminal_proceeding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное дело'),
        ),
        migrations.AddField(
            model_name='notification',
            name='jurisdiction_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.jurisdictioncheck', verbose_name='Проверка подсудности'),
        ),
        migrations.AddField(
            model_name='notification',
            name='kas_proceeding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrative_proceedings.kasproceedings', verbose_name='Дело по КАС'),
        ),
        migrations.AddField(
            model_name='notification',
            name='legal_references',
            field=models.ManyToManyField(blank=True, to='notifications.legalreference', verbose_name='Правовые ссылки'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
