# Generated by Django 4.2.7 on 2024-02-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidescaseincase',
            name='petitionsincase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='petitionsincase', to='business_card.petitionsincase', verbose_name='Карточка на дело'),
        ),
    ]
