# Generated by Django 4.2.7 on 2024-02-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='decision_appeal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='в апелляции отказано/удовлетворенно'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='meeting_requirements',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='выполнение требований УПК, перед направлением дела'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='notification_parties',
            field=models.ManyToManyField(blank=True, null=True, to='business_card.sidescaseincase', verbose_name='Уведомление сторон об апелляции'),
        ),
        migrations.AlterField(
            model_name='consideredcase',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата вступления в законную силу'),
        ),
        migrations.AlterField(
            model_name='consideredcase',
            name='executive_lists',
            field=models.DateField(blank=True, null=True, verbose_name='Дата исполнения дела'),
        ),
        migrations.AlterField(
            model_name='executioncase',
            name='executive_lists',
            field=models.DateField(blank=True, null=True, verbose_name='Дата исполнения дела'),
        ),
        migrations.AlterField(
            model_name='executioncase',
            name='notification_parties',
            field=models.ManyToManyField(blank=True, null=True, to='business_card.sidescase', verbose_name='Уведомление сторон об исполнении'),
        ),
    ]
