# Generated by Django 4.2.7 on 2024-02-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_alter_appeal_decision_appeal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executioncase',
            options={'verbose_name': 'Дело рассмотрено'},
        ),
        migrations.AlterField(
            model_name='familiarizationcase',
            name='amount_one_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='сумма за один день ознакомления'),
        ),
        migrations.AlterField(
            model_name='familiarizationcase',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='familiarizationcase',
            name='number_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество дней'),
        ),
        migrations.AlterField(
            model_name='familiarizationcase',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='общая сумма вознаграждения по постановлению'),
        ),
    ]
