# Generated by Django 4.2.7 on 2024-02-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0003_alter_executioncase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiarizationcase',
            name='familiarization',
            field=models.ManyToManyField(to='business_card.sidescase', verbose_name='Ознакомление с материалами дела'),
        ),
    ]
