# Generated by Django 4.2.7 on 2024-02-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0004_familiarizationcase_familiarization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiarizationcase',
            name='familiarization',
        ),
    ]
