# Generated by Django 4.2.7 on 2024-02-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0005_remove_familiarizationcase_familiarization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiarizationcase',
            old_name='notification_parties',
            new_name='sides_case',
        ),
    ]
