# Generated by Django 4.2.7 on 2024-02-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0006_rename_notification_parties_familiarizationcase_sides_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiarizationcase',
            old_name='sides_case',
            new_name='notification_parties',
        ),
    ]
