# Generated by Django 6.0.1 on 2026-04-14 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Тип уведомления',
                'verbose_name_plural': 'Типы уведомлений',
            },
        ),
        migrations.CreateModel(
            name='ProgressActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название действия')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Тип действия',
                'verbose_name_plural': 'Типы действий',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('case_object_id', models.PositiveIntegerField()),
                ('sent_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время вручения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('delivered', 'Вручено/Доставлено'), ('failed', 'Ошибка доставки')], default='sent', max_length=20, verbose_name='Статус')),
                ('recipient_address', models.TextField(blank=True, null=True, verbose_name='Адрес получателя (для почты)')),
                ('recipient_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона (для СМС/звонка)')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('case_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_management_case_notifications', to='contenttypes.contenttype')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_management_notifications', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_management_created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='case_management.notificationtype', verbose_name='Тип уведомления')),
            ],
            options={
                'verbose_name': 'Извещение',
                'verbose_name_plural': 'Извещения',
                'db_table': 'case_management_notifications',
                'ordering': ['-sent_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_object_id', models.PositiveIntegerField()),
                ('description', models.TextField(verbose_name='Описание действия')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('action_date', models.DateField(verbose_name='Дата действия')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_management_progress_entries', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
                ('case_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_management_progress_entries', to='contenttypes.contenttype')),
                ('related_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_entries', to='case_management.notification', verbose_name='Связанное извещение')),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='case_management.progressactiontype', verbose_name='Действие')),
            ],
            options={
                'verbose_name': 'Запись справочного листа',
                'verbose_name_plural': 'Записи справочного листа',
                'db_table': 'case_management_progress_entries',
                'ordering': ['-action_date', '-created_date'],
            },
        ),
    ]
