# Generated by Django 6.0.1 on 2026-04-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_object_id', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание действия')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('action_date', models.DateField(verbose_name='Дата действия')),
            ],
            options={
                'verbose_name': 'Запись справочного листа',
                'verbose_name_plural': 'Записи справочного листа',
                'db_table': 'case_management_progress_entries',
                'ordering': ['-action_date', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('delivery_method', models.CharField(choices=[('post', 'Почта России (заказное письмо)'), ('email', 'Электронная почта'), ('sms', 'СМС-сообщение'), ('phone_call', 'Телефонограмма'), ('telegram', 'Телеграмма'), ('fax', 'Факсимильная связь'), ('in_person', 'Вручено лично под расписку'), ('via_representative', 'Через представителя (администрация/семья)'), ('electronic_summon', 'Электронная повестка (ГАС Правосудие)'), ('vks', 'Видео-конференц-связь'), ('detention_facility', 'Требование в СИЗО (форма №33/№37)')], max_length=30, verbose_name='Способ доставки')),
                ('case_object_id', models.PositiveIntegerField()),
                ('notification_text', models.TextField(blank=True, null=True, verbose_name='Текст уведомления')),
                ('sent_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время вручения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('delivered', 'Вручено/Доставлено'), ('failed', 'Ошибка доставки')], default='sent', max_length=20, verbose_name='Статус')),
                ('recipient_address', models.TextField(blank=True, null=True, verbose_name='Адрес получателя (для почты)')),
                ('recipient_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона (для СМС/звонка)')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('consent_sms', models.BooleanField(default=False, verbose_name='Согласие на СМС-уведомление')),
                ('consent_email', models.BooleanField(default=False, verbose_name='Согласие на Email-уведомление')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('hearing_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время заседания')),
                ('hearing_room', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зал суда')),
            ],
            options={
                'verbose_name': 'Извещение',
                'verbose_name_plural': 'Извещения',
                'db_table': 'case_management_notifications',
                'ordering': ['-sent_date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('case_category', models.CharField(choices=[('criminal', 'Уголовное дело'), ('civil', 'Гражданское дело'), ('administrative', 'Административное дело (КАС)'), ('coap', 'Дело об административном правонарушении (КоАП)')], max_length=20, verbose_name='Категория дела')),
                ('participant_type', models.CharField(choices=[('defendant', 'Подсудимый / Ответчик'), ('side', 'Истец / Свидетель'), ('victim', 'Потерпевший'), ('witness', 'Свидетель'), ('expert', 'Эксперт / Специалист / Переводчик'), ('representative', 'Представитель / Адвокат'), ('inmate', 'Подсудимый под стражей (требование о доставке)')], max_length=20, verbose_name='Тип участника')),
                ('content', models.TextField(verbose_name='Содержимое шаблона')),
                ('form_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер формы')),
                ('variables_description', models.TextField(blank=True, null=True, verbose_name='Описание переменных')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Шаблон повестки',
                'verbose_name_plural': 'Шаблоны повесток',
                'ordering': ['case_category', 'participant_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Тип уведомления',
                'verbose_name_plural': 'Типы уведомлений',
            },
        ),
        migrations.CreateModel(
            name='ProgressActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название действия')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Тип действия',
                'verbose_name_plural': 'Типы действий',
            },
        ),
    ]
