# Generated by Django 6.0.1 on 2026-04-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDeadlineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('criminal', 'Уголовное дело'), ('civil', 'Гражданское дело'), ('coap', 'Дело об АП (КоАП)'), ('kas', 'Административное дело (КАС)'), ('other', 'Иной материал')], max_length=20, unique=True, verbose_name='Категория дела')),
                ('appointment_deadline_simple', models.PositiveIntegerField(default=14, verbose_name='Срок назначения (простые дела, дней)')),
                ('appointment_deadline_complex', models.PositiveIntegerField(default=30, verbose_name='Срок назначения (сложные дела, дней)')),
                ('trial_start_deadline', models.PositiveIntegerField(default=14, verbose_name='Срок начала судебного разбирательства (дней)')),
                ('civil_preparation_deadline', models.PositiveIntegerField(default=30, verbose_name='Срок подготовки дела (дней)')),
                ('civil_consideration_deadline', models.PositiveIntegerField(default=60, verbose_name='Срок рассмотрения дела (дней)')),
                ('kas_consideration_deadline', models.PositiveIntegerField(default=30, verbose_name='Срок рассмотрения дела (дней)')),
                ('kas_appeal_deadline', models.PositiveIntegerField(default=30, verbose_name='Срок обжалования (дней)')),
                ('coap_consideration_deadline', models.PositiveIntegerField(default=15, verbose_name='Срок рассмотрения дела (дней)')),
                ('coap_appeal_deadline', models.PositiveIntegerField(default=10, verbose_name='Срок обжалования (дней)')),
                ('other_consideration_deadline', models.PositiveIntegerField(default=30, verbose_name='Срок рассмотрения (дней)')),
                ('enable_deadline_tracking', models.BooleanField(default=True, verbose_name='Включить отслеживание сроков')),
                ('enable_violation_alerts', models.BooleanField(default=True, verbose_name='Включить оповещения о нарушениях')),
            ],
            options={
                'verbose_name': 'Настройка сроков',
                'verbose_name_plural': 'Настройки сроков',
            },
        ),
        migrations.CreateModel(
            name='CaseProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_object_id', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание действия')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('action_date', models.DateField(verbose_name='Дата действия')),
            ],
            options={
                'verbose_name': 'Запись справочного листа',
                'verbose_name_plural': 'Записи справочного листа',
                'db_table': 'case_management_progress_entries',
                'ordering': ['-action_date', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='DeadlineViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_object_id', models.PositiveIntegerField()),
                ('deadline_type', models.CharField(max_length=100, verbose_name='Тип срока')),
                ('deadline_days', models.PositiveIntegerField(verbose_name='Установленный срок (дней)')),
                ('actual_days', models.PositiveIntegerField(verbose_name='Фактическое количество дней')),
                ('violation_date', models.DateField(auto_now_add=True, verbose_name='Дата фиксации нарушения')),
                ('resolved', models.BooleanField(default=False, verbose_name='Нарушение устранено')),
                ('resolved_date', models.DateField(blank=True, null=True, verbose_name='Дата устранения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Нарушение срока',
                'verbose_name_plural': 'Нарушения сроков',
                'ordering': ['-violation_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_object_id', models.PositiveIntegerField(verbose_name='ID дела')),
                ('participant_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID участника')),
                ('participant_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО/Наименование участника')),
                ('participant_role', models.CharField(blank=True, max_length=200, verbose_name='Роль в деле')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_address', models.TextField(blank=True, verbose_name='Почтовый адрес')),
                ('hearing_date', models.DateField(verbose_name='Дата заседания')),
                ('hearing_time', models.TimeField(verbose_name='Время заседания')),
                ('hearing_room', models.CharField(blank=True, max_length=50, verbose_name='Номер зала')),
                ('message_text', models.TextField(verbose_name='Текст уведомления')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата вручения')),
                ('return_reason', models.TextField(blank=True, verbose_name='Причина возврата/не вручения')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Дата возврата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название канала')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('requires_confirmation', models.BooleanField(default=False, verbose_name='Требует подтверждения вручения')),
            ],
            options={
                'verbose_name': 'Канал уведомления',
                'verbose_name_plural': 'Каналы уведомлений',
            },
        ),
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название статуса')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальный статус')),
                ('is_success', models.BooleanField(default=False, verbose_name='Успешное завершение')),
            ],
            options={
                'verbose_name': 'Статус уведомления',
                'verbose_name_plural': 'Статусы уведомлений',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('case_category', models.CharField(choices=[('criminal', 'Уголовное дело'), ('civil', 'Гражданское дело'), ('coap', 'Дело об АП (КоАП)'), ('kas', 'Административное дело (КАС)')], max_length=20, verbose_name='Категория дела')),
                ('participant_type', models.CharField(choices=[('defendant', 'Подсудимый/Обвиняемый'), ('side', 'Сторона'), ('lawyer', 'Адвокат/Представитель')], max_length=20, verbose_name='Тип участника')),
                ('form_number', models.CharField(blank=True, max_length=20, verbose_name='Номер формы (по инструкции)')),
                ('content', models.TextField(verbose_name='Содержание шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомлений',
                'ordering': ['case_category', 'participant_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProgressActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название действия')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('case_category', models.CharField(blank=True, choices=[('criminal', 'Уголовное дело'), ('civil', 'Гражданское дело'), ('coap', 'Дело об АП (КоАП)'), ('kas', 'Административное дело (КАС)'), ('other', 'Иной материал'), ('common', 'Общее для всех')], max_length=20, null=True, verbose_name='Категория дела')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип действия',
                'verbose_name_plural': 'Типы действий',
                'ordering': ['case_category', 'order', 'name'],
            },
        ),
    ]
