# Generated by Django 6.0.1 on 2026-04-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_management', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caseprogressentry',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_management_progress_entries', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил'),
        ),
        migrations.AddField(
            model_name='caseprogressentry',
            name='case_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_management_progress_entries', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='case_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_management_case_notifications', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_management_notifications', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_management_created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='caseprogressentry',
            name='related_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_entries', to='case_management.notification', verbose_name='Связанное извещение'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('case_category', 'participant_type')},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_management.notificationtemplate', verbose_name='Шаблон повестки'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='case_management.notificationtype', verbose_name='Тип уведомления'),
        ),
        migrations.AddField(
            model_name='caseprogressentry',
            name='action_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='case_management.progressactiontype', verbose_name='Действие'),
        ),
    ]
