# Generated by Django 6.0.1 on 2026-04-22 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_management', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caseprogressentry',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_management_progress_entries', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил'),
        ),
        migrations.AddField(
            model_name='caseprogressentry',
            name='case_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_management_progress_entries', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='deadlineviolation',
            name='case_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='case_content_type',
            field=models.ForeignKey(limit_choices_to={'app_label__in': ['criminal_proceedings', 'civil_proceedings', 'administrative_proceedings', 'kas_proceedings']}, on_delete=django.db.models.deletion.CASCADE, related_name='case_management_case_notifications', to='contenttypes.contenttype', verbose_name='Тип дела'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='notification',
            name='participant_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['sidescaseincase', 'lawyer', 'defendant']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_management_participant_notifications', to='contenttypes.contenttype', verbose_name='Тип участника'),
        ),
        migrations.AddField(
            model_name='notification',
            name='progress_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='case_management.caseprogressentry', verbose_name='Запись в справочном листе'),
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='case_management.notificationchannel', verbose_name='Канал уведомления'),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='case_management.notificationstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_management.notificationtemplate', verbose_name='Использованный шаблон'),
        ),
        migrations.AddField(
            model_name='caseprogressentry',
            name='action_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='case_management.progressactiontype', verbose_name='Действие'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['case_content_type', 'case_object_id'], name='case_manage_case_co_cd20ad_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['participant_content_type', 'participant_object_id'], name='case_manage_partici_1518c6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'sent_date'], name='case_manage_status__e88c2b_idx'),
        ),
    ]
