# Generated by Django 6.0.1 on 2026-04-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivery_method',
            field=models.CharField(choices=[('post', 'Почта России'), ('email', 'Электронная почта'), ('sms', 'СМС-сообщение'), ('phone_call', 'Телефонограмма'), ('telegram', 'Телеграмма'), ('in_person', 'Вручено лично'), ('via_representative', 'Через дознавателя/следователя')], default=222, max_length=20, verbose_name='Способ доставки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caseprogressentry',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание действия'),
        ),
    ]
