# Generated by Django 6.0.4 on 2026-04-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0002_notification_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='case_category',
            field=models.CharField(blank=True, choices=[('criminal', 'Уголовное дело'), ('civil', 'Гражданское дело'), ('admin_offense', 'Дело об административном правонарушении'), ('administrative', 'Административное дело (КАС)')], max_length=50, null=True, verbose_name='Категория дела'),
        ),
        migrations.AddField(
            model_name='notification',
            name='hearing_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время заседания'),
        ),
        migrations.AddField(
            model_name='notification',
            name='summons_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст повестки'),
        ),
    ]
