# Generated by Django 6.0.4 on 2026-04-18 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название канала')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Канал уведомления',
                'verbose_name_plural': 'Каналы уведомлений',
            },
        ),
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название статуса')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальный статус')),
            ],
            options={
                'verbose_name': 'Статус уведомления',
                'verbose_name_plural': 'Статусы уведомлений',
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='case_content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_template',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='caseprogressentry',
            name='related_notification',
        ),
        migrations.CreateModel(
            name='CaseParticipantNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_object_id', models.PositiveIntegerField()),
                ('participant_type', models.CharField(max_length=50, verbose_name='Тип участника')),
                ('participant_id', models.PositiveIntegerField(verbose_name='ID участника')),
                ('hearing_date', models.DateField(verbose_name='Дата судебного заседания')),
                ('hearing_time', models.TimeField(blank=True, null=True, verbose_name='Время судебного заседания')),
                ('sent_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата направления')),
                ('delivered_date', models.DateField(blank=True, null=True, verbose_name='Дата вручения')),
                ('delivery_notes', models.TextField(blank=True, default='', verbose_name='Примечания по вручению')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Почтовый/трекинг номер')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Номер телефона (для СМС/звонка)')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email (для электронной почты)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_notifications', to='contenttypes.contenttype')),
                ('progress_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='case_management.caseprogressentry', verbose_name='Запись в справочном листе')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='case_management.notificationchannel', verbose_name='Канал уведомления')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='case_management.notificationstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Извещение участника',
                'verbose_name_plural': 'Извещения участников',
                'ordering': ['-sent_date'],
            },
        ),
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
        migrations.DeleteModel(
            name='NotificationType',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddIndex(
            model_name='caseparticipantnotification',
            index=models.Index(fields=['case_content_type', 'case_object_id'], name='case_manage_case_co_7467a1_idx'),
        ),
        migrations.AddIndex(
            model_name='caseparticipantnotification',
            index=models.Index(fields=['participant_type', 'participant_id'], name='case_manage_partici_ce7098_idx'),
        ),
        migrations.AddIndex(
            model_name='caseparticipantnotification',
            index=models.Index(fields=['hearing_date'], name='case_manage_hearing_4a690d_idx'),
        ),
    ]
