# Generated by Django 6.0.4 on 2026-04-19 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0003_notificationchannel_notificationstatus_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_object_id', models.PositiveIntegerField(verbose_name='ID дела')),
                ('participant_object_id', models.PositiveIntegerField(verbose_name='ID участника')),
                ('participant_name', models.CharField(max_length=255, verbose_name='ФИО/Наименование участника')),
                ('participant_role', models.CharField(blank=True, max_length=200, verbose_name='Роль в деле')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_address', models.TextField(blank=True, verbose_name='Почтовый адрес')),
                ('hearing_date', models.DateField(verbose_name='Дата заседания')),
                ('hearing_time', models.TimeField(verbose_name='Время заседания')),
                ('hearing_room', models.CharField(blank=True, max_length=50, verbose_name='Номер зала')),
                ('message_text', models.TextField(verbose_name='Текст уведомления')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата вручения')),
                ('return_reason', models.TextField(blank=True, verbose_name='Причина возврата/не вручения')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Дата возврата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('case_category', models.CharField(choices=[('criminal', 'Уголовное дело'), ('civil', 'Гражданское дело'), ('coap', 'Дело об АП (КоАП)'), ('kas', 'Административное дело (КАС)')], max_length=20, verbose_name='Категория дела')),
                ('participant_type', models.CharField(choices=[('defendant', 'Подсудимый/Обвиняемый'), ('side', 'Сторона'), ('lawyer', 'Адвокат/Представитель')], max_length=20, verbose_name='Тип участника')),
                ('form_number', models.CharField(blank=True, max_length=20, verbose_name='Номер формы (по инструкции)')),
                ('content', models.TextField(verbose_name='Содержание шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомлений',
                'ordering': ['case_category', 'participant_type', 'order'],
            },
        ),
        migrations.RemoveIndex(
            model_name='caseparticipantnotification',
            name='case_manage_case_co_7467a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='caseparticipantnotification',
            name='case_manage_partici_ce7098_idx',
        ),
        migrations.RemoveIndex(
            model_name='caseparticipantnotification',
            name='case_manage_hearing_4a690d_idx',
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='requires_confirmation',
            field=models.BooleanField(default=False, verbose_name='Требует подтверждения вручения'),
        ),
        migrations.AddField(
            model_name='notificationstatus',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='Успешное завершение'),
        ),
        migrations.AddField(
            model_name='notification',
            name='case_content_type',
            field=models.ForeignKey(limit_choices_to={'app_label__in': ['criminal_proceedings', 'civil_proceedings', 'administrative_proceedings', 'kas_proceedings']}, on_delete=django.db.models.deletion.CASCADE, related_name='case_management_case_notifications', to='contenttypes.contenttype', verbose_name='Тип дела'),
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='case_management.notificationchannel', verbose_name='Канал уведомления'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='notification',
            name='participant_content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['sidescaseincase', 'lawyer', 'defendant']}, on_delete=django.db.models.deletion.CASCADE, related_name='case_management_participant_notifications', to='contenttypes.contenttype', verbose_name='Тип участника'),
        ),
        migrations.AddField(
            model_name='notification',
            name='progress_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='case_management.caseprogressentry', verbose_name='Запись в справочном листе'),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='case_management.notificationstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_management.notificationtemplate', verbose_name='Использованный шаблон'),
        ),
        migrations.RemoveField(
            model_name='caseparticipantnotification',
            name='case_content_type',
        ),
        migrations.RemoveField(
            model_name='caseparticipantnotification',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='caseparticipantnotification',
            name='progress_entry',
        ),
        migrations.RemoveField(
            model_name='caseparticipantnotification',
            name='status',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['case_content_type', 'case_object_id'], name='case_manage_case_co_cd20ad_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['participant_content_type', 'participant_object_id'], name='case_manage_partici_1518c6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'sent_date'], name='case_manage_status__e88c2b_idx'),
        ),
        migrations.DeleteModel(
            name='CaseParticipantNotification',
        ),
    ]
