# Generated by Django 6.0.4 on 2026-04-16 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0003_notification_case_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='hearing_datetime',
            new_name='hearing_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='case_category',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='summons_text',
        ),
        migrations.AddField(
            model_name='notification',
            name='consent_email',
            field=models.BooleanField(default=False, verbose_name='Согласие на Email-уведомление'),
        ),
        migrations.AddField(
            model_name='notification',
            name='consent_sms',
            field=models.BooleanField(default=False, verbose_name='Согласие на СМС-уведомление'),
        ),
        migrations.AddField(
            model_name='notification',
            name='hearing_room',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Зал суда'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='delivery_method',
            field=models.CharField(choices=[('post', 'Почта России (заказное письмо)'), ('email', 'Электронная почта'), ('sms', 'СМС-сообщение'), ('phone_call', 'Телефонограмма'), ('telegram', 'Телеграмма'), ('fax', 'Факсимильная связь'), ('in_person', 'Вручено лично под расписку'), ('via_representative', 'Через представителя (администрация/семья)'), ('electronic_summon', 'Электронная повестка (ГАС Правосудие)'), ('vks', 'Видео-конференц-связь'), ('detention_facility', 'Требование в СИЗО (форма №33/№37)')], max_length=30, verbose_name='Способ доставки'),
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('case_category', models.CharField(choices=[('criminal', 'Уголовное дело'), ('civil', 'Гражданское дело'), ('administrative', 'Административное дело (КАС)'), ('coap', 'Дело об административном правонарушении (КоАП)')], max_length=20, verbose_name='Категория дела')),
                ('participant_type', models.CharField(choices=[('defendant', 'Подсудимый / Ответчик'), ('side', 'Сторона (истец/ответчик)'), ('victim', 'Потерпевший'), ('witness', 'Свидетель'), ('expert', 'Эксперт / Специалист / Переводчик'), ('representative', 'Представитель / Адвокат'), ('inmate', 'Подсудимый под стражей (требование о доставке)')], max_length=20, verbose_name='Тип участника')),
                ('content', models.TextField(verbose_name='Содержимое шаблона')),
                ('form_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер формы')),
                ('variables_description', models.TextField(blank=True, null=True, verbose_name='Описание переменных')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Шаблон повестки',
                'verbose_name_plural': 'Шаблоны повесток',
                'ordering': ['case_category', 'participant_type', 'order'],
                'unique_together': {('case_category', 'participant_type')},
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_management.notificationtemplate', verbose_name='Шаблон повестки'),
        ),
    ]
