# Generated by Django 6.0.4 on 2026-04-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0004_rename_hearing_datetime_notification_hearing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='participant_type',
            field=models.CharField(choices=[('defendant', 'Подсудимый / Ответчик'), ('side', 'Истец / Свидетель'), ('victim', 'Потерпевший'), ('witness', 'Свидетель'), ('expert', 'Эксперт / Специалист / Переводчик'), ('representative', 'Представитель / Адвокат'), ('inmate', 'Подсудимый под стражей (требование о доставке)')], max_length=20, verbose_name='Тип участника'),
        ),
    ]
