# Generated by Django 6.0.4 on 2026-04-19 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0004_notification_notificationtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='case_management.notificationchannel', verbose_name='Канал уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='participant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО/Наименование участника'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='case_management.notificationstatus', verbose_name='Статус'),
        ),
    ]
