# Generated by Django 6.0.4 on 2026-04-19 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0005_alter_notification_channel_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='participant_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['sidescaseincase', 'lawyer', 'defendant']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_management_participant_notifications', to='contenttypes.contenttype', verbose_name='Тип участника'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='participant_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID участника'),
        ),
    ]
