# Generated by Django 6.0.1 on 2026-04-20 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0006_alter_notification_participant_content_type_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDeadlineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('criminal', 'Уголовное дело'), ('civil', 'Гражданское дело'), ('coap', 'Дело об АП (КоАП)'), ('kas', 'Административное дело (КАС)'), ('other', 'Иной материал')], max_length=20, unique=True, verbose_name='Категория дела')),
                ('appointment_deadline_simple', models.PositiveIntegerField(default=14, verbose_name='Срок назначения (простые дела, дней)')),
                ('appointment_deadline_complex', models.PositiveIntegerField(default=30, verbose_name='Срок назначения (сложные дела, дней)')),
                ('trial_start_deadline', models.PositiveIntegerField(default=14, verbose_name='Срок начала судебного разбирательства (дней)')),
                ('civil_preparation_deadline', models.PositiveIntegerField(default=30, verbose_name='Срок подготовки дела (дней)')),
                ('civil_consideration_deadline', models.PositiveIntegerField(default=60, verbose_name='Срок рассмотрения дела (дней)')),
                ('kas_consideration_deadline', models.PositiveIntegerField(default=30, verbose_name='Срок рассмотрения дела (дней)')),
                ('kas_appeal_deadline', models.PositiveIntegerField(default=30, verbose_name='Срок обжалования (дней)')),
                ('coap_consideration_deadline', models.PositiveIntegerField(default=15, verbose_name='Срок рассмотрения дела (дней)')),
                ('coap_appeal_deadline', models.PositiveIntegerField(default=10, verbose_name='Срок обжалования (дней)')),
                ('other_consideration_deadline', models.PositiveIntegerField(default=30, verbose_name='Срок рассмотрения (дней)')),
                ('enable_deadline_tracking', models.BooleanField(default=True, verbose_name='Включить отслеживание сроков')),
                ('enable_violation_alerts', models.BooleanField(default=True, verbose_name='Включить оповещения о нарушениях')),
            ],
            options={
                'verbose_name': 'Настройка сроков',
                'verbose_name_plural': 'Настройки сроков',
            },
        ),
        migrations.AlterModelOptions(
            name='progressactiontype',
            options={'ordering': ['case_category', 'order', 'name'], 'verbose_name': 'Тип действия', 'verbose_name_plural': 'Типы действий'},
        ),
        migrations.AddField(
            model_name='progressactiontype',
            name='case_category',
            field=models.CharField(blank=True, choices=[('criminal', 'Уголовное дело'), ('civil', 'Гражданское дело'), ('coap', 'Дело об АП (КоАП)'), ('kas', 'Административное дело (КАС)'), ('other', 'Иной материал'), ('common', 'Общее для всех')], max_length=20, null=True, verbose_name='Категория дела'),
        ),
        migrations.AddField(
            model_name='progressactiontype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='progressactiontype',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.CreateModel(
            name='DeadlineViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_object_id', models.PositiveIntegerField()),
                ('deadline_type', models.CharField(max_length=100, verbose_name='Тип срока')),
                ('deadline_days', models.PositiveIntegerField(verbose_name='Установленный срок (дней)')),
                ('actual_days', models.PositiveIntegerField(verbose_name='Фактическое количество дней')),
                ('violation_date', models.DateField(auto_now_add=True, verbose_name='Дата фиксации нарушения')),
                ('resolved', models.BooleanField(default=False, verbose_name='Нарушение устранено')),
                ('resolved_date', models.DateField(blank=True, null=True, verbose_name='Дата устранения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('case_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Нарушение срока',
                'verbose_name_plural': 'Нарушения сроков',
                'ordering': ['-violation_date'],
            },
        ),
    ]
