# Generated by Django 6.0.1 on 2026-04-22 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrative_proceedings', '0001_initial'),
        ('business_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kascasemovement',
            name='business_movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kas_movements', to='business_card.businessmovement', verbose_name='Движение дела (из business_card)'),
        ),
        migrations.AddField(
            model_name='kaslawyer',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kas_lawyers', to='business_card.lawyer', verbose_name='Представитель (данные из business_card)'),
        ),
        migrations.AddField(
            model_name='kaslawyer',
            name='sides_case_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kas_lawyers', to='business_card.sidescase', verbose_name='Представитель какой стороны'),
        ),
        migrations.AddField(
            model_name='kaspetition',
            name='petitions_incase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kas_petitions', to='business_card.petitionsincase', verbose_name='Ходатайство'),
        ),
    ]
