# Generated by Django 6.0.1 on 2026-04-22 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrative_proceedings', '0002_initial'),
        ('business_card', '0001_initial'),
        ('case_registry', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kasproceedings',
            name='presiding_judge',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'judge'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Судья (председательствующий)'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='registered_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kas_proceedings_link', to='case_registry.registeredcase', verbose_name='Зарегистрированное дело'),
        ),
        migrations.AddField(
            model_name='kaspetition',
            name='kas_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kas_petitions', to='administrative_proceedings.kasproceedings', verbose_name='Производство КАС'),
        ),
        migrations.AddField(
            model_name='kaslawyer',
            name='kas_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kas_lawyers', to='administrative_proceedings.kasproceedings', verbose_name='Производство КАС'),
        ),
        migrations.AddField(
            model_name='kasexecution',
            name='kas_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kas_executions', to='administrative_proceedings.kasproceedings', verbose_name='Производство КАС'),
        ),
        migrations.AddField(
            model_name='kasdecision',
            name='kas_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kas_decisions', to='administrative_proceedings.kasproceedings', verbose_name='Производство КАС'),
        ),
        migrations.AddField(
            model_name='kascasemovement',
            name='kas_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kas_movements', to='administrative_proceedings.kasproceedings', verbose_name='Производство КАС'),
        ),
        migrations.AddField(
            model_name='kassidescaseincase',
            name='kas_proceedings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kas_sides', to='administrative_proceedings.kasproceedings', verbose_name='Производство КАС'),
        ),
        migrations.AddField(
            model_name='kassidescaseincase',
            name='sides_case_incase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kas_sides', to='business_card.sidescaseincase', verbose_name='Данные стороны (ФИО/наименование, контакты)'),
        ),
        migrations.AddField(
            model_name='kassidescaseincase',
            name='sides_case_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kas_sides', to='business_card.sidescase', verbose_name='Роль стороны (адм. истец, адм. ответчик, заинтересованное лицо и т.д.)'),
        ),
        migrations.AddIndex(
            model_name='kaspetition',
            index=models.Index(fields=['petitioner_type', 'petitioner_id'], name='administrat_petitio_a739bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kassidescaseincase',
            unique_together={('kas_proceedings', 'sides_case_incase', 'sides_case_role')},
        ),
    ]
