# Generated by Django 6.0.1 on 2026-04-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_proceedings', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Порядок поступления',
                'verbose_name_plural': 'Порядок поступления',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AppealResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Результат апелляции',
                'verbose_name_plural': 'Результаты апелляции',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CassationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Результат кассации',
                'verbose_name_plural': 'Результаты кассации',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExpertiseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид экспертизы',
                'verbose_name_plural': 'Виды экспертиз',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Результат рассмотрения',
                'verbose_name_plural': 'Результаты рассмотрения',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PostponementReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Причина отложения',
                'verbose_name_plural': 'Причины отложения',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PreliminaryProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Мера предварительной защиты',
                'verbose_name_plural': 'Меры предварительной защиты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SuspensionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Причина приостановления',
                'verbose_name_plural': 'Причины приостановления',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TermCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Соблюдение сроков',
                'verbose_name_plural': 'Соблюдение сроков',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='kasdecision',
            name='appeal_date',
        ),
        migrations.RemoveField(
            model_name='kasdecision',
            name='appeal_deadline_for_corrections',
        ),
        migrations.RemoveField(
            model_name='kasdecision',
            name='appeal_result',
        ),
        migrations.RemoveField(
            model_name='kasdecision',
            name='appeal_return_reason',
        ),
        migrations.RemoveField(
            model_name='kasdecision',
            name='appeal_returned_without_review_date',
        ),
        migrations.RemoveField(
            model_name='kasdecision',
            name='appeal_review_date',
        ),
        migrations.RemoveField(
            model_name='kasdecision',
            name='appeal_scheduled_date',
        ),
        migrations.RemoveField(
            model_name='kasdecision',
            name='appeal_scheduled_date_repeated',
        ),
        migrations.RemoveField(
            model_name='kasdecision',
            name='appeal_sent_to_higher_court_date',
        ),
        migrations.RemoveField(
            model_name='kasdecision',
            name='appeal_sent_to_higher_court_repeated',
        ),
        migrations.RemoveField(
            model_name='kasdecision',
            name='appeal_type',
        ),
        migrations.RemoveField(
            model_name='kasdecision',
            name='appealed_by',
        ),
        migrations.RemoveField(
            model_name='kasdecision',
            name='cassation_result',
        ),
        migrations.RemoveField(
            model_name='kasdecision',
            name='cassation_ruling_date',
        ),
        migrations.RemoveField(
            model_name='kasdecision',
            name='is_appealed',
        ),
        migrations.RemoveField(
            model_name='kasproceedings',
            name='postponement_reason_code',
        ),
        migrations.AddField(
            model_name='kasdecision',
            name='decision_appeal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подачи апелляционной жалобы на решение'),
        ),
        migrations.AddField(
            model_name='kasdecision',
            name='decision_appeal_result',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Результат апелляционного обжалования решения'),
        ),
        migrations.AddField(
            model_name='kasdecision',
            name='decision_appeal_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рассмотрения апелляции на решение'),
        ),
        migrations.AddField(
            model_name='kasdecision',
            name='decision_cassation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подачи кассационной жалобы на решение'),
        ),
        migrations.AddField(
            model_name='kasdecision',
            name='decision_cassation_result',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Результат кассационного обжалования решения'),
        ),
        migrations.AddField(
            model_name='kasdecision',
            name='decision_cassation_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рассмотрения кассации на решение'),
        ),
        migrations.AddField(
            model_name='kasdecision',
            name='decision_is_appealed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Решение обжаловано в апелляции'),
        ),
        migrations.AddField(
            model_name='kasdecision',
            name='decision_is_cassation_filed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Решение обжаловано в кассации'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='appeal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подачи апелляционной жалобы/представления'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='appeal_deadline_for_corrections',
            field=models.DateField(blank=True, null=True, verbose_name='Срок для устранения недостатков апелляционной жалобы до'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='appeal_result',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Результат апелляционного рассмотрения'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='appeal_return_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина возврата апелляционной жалобы'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='appeal_returned_without_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата возврата апелляционной жалобы без рассмотрения'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='appeal_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рассмотрения дела в апелляционной инстанции'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='appeal_scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дело назначено к рассмотрению в апелляции на'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='appeal_scheduled_date_repeated',
            field=models.DateField(blank=True, null=True, verbose_name='Повторно назначено в апелляции на'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='appeal_sent_to_higher_court_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата направления дела в апелляционный суд'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='appeal_sent_to_higher_court_repeated',
            field=models.DateField(blank=True, null=True, verbose_name='Дата повторного направления в апелляционный суд'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='appeal_type',
            field=models.CharField(blank=True, choices=[('1', 'Жалоба'), ('2', 'Представление прокурора')], max_length=2, null=True, verbose_name='Тип обжалования (апелляция)'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='appealed_by',
            field=models.TextField(blank=True, null=True, verbose_name='Кем обжаловано (апелляция)'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='cassation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подачи кассационной жалобы/представления'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='cassation_deadline_for_corrections',
            field=models.DateField(blank=True, null=True, verbose_name='Срок для устранения недостатков кассационной жалобы до'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='cassation_filed_by',
            field=models.TextField(blank=True, null=True, verbose_name='Кем подана кассационная жалоба/представление'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='cassation_result',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Результат кассационного рассмотрения'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='cassation_return_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина возврата кассационной жалобы'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='cassation_returned_without_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата возврата кассационной жалобы без рассмотрения'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='cassation_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рассмотрения дела в кассационной инстанции'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='cassation_scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дело назначено к рассмотрению в кассации на'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='cassation_sent_to_higher_court_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата направления дела в кассационный суд'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='cassation_type',
            field=models.CharField(blank=True, choices=[('1', 'Жалоба'), ('2', 'Представление прокурора')], max_length=2, null=True, verbose_name='Тип обжалования (кассация)'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='is_appealed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Обжаловано (апелляция)'),
        ),
        migrations.AddField(
            model_name='kasproceedings',
            name='is_cassation_filed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Подана кассационная жалоба/представление'),
        ),
        migrations.AlterField(
            model_name='kasdecision',
            name='outcome',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Результат рассмотрения (основное требование)'),
        ),
        migrations.AlterField(
            model_name='kasdecision',
            name='term_compliance',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Дело рассмотрено в сроки'),
        ),
        migrations.AlterField(
            model_name='kasproceedings',
            name='admission_order',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Порядок поступления'),
        ),
        migrations.AlterField(
            model_name='kasproceedings',
            name='postponement_reason',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Причина отложения'),
        ),
        migrations.AlterField(
            model_name='kasproceedings',
            name='preliminary_protection',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Меры предварительной защиты'),
        ),
        migrations.AlterField(
            model_name='kasproceedings',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Основание приостановления'),
        ),
    ]
