# Generated by Django 6.0.1 on 2026-02-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала отсутствия')),
                ('end_date', models.DateField(verbose_name='Дата окончания отсутствия')),
                ('block_start_date', models.DateField(verbose_name='Начало блокировки распределения')),
                ('block_end_date', models.DateField(verbose_name='Окончание блокировки распределения')),
                ('reason', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Запись отсутствия',
                'verbose_name_plural': 'Записи отсутствий',
                'ordering': ['-block_start_date'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='Цвет в календаре')),
                ('block_before_days', models.PositiveIntegerField(default=0, verbose_name='Дней до начала для блокировки')),
                ('block_after_days', models.PositiveIntegerField(default=0, verbose_name='Дней после окончания для блокировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип отсутствия',
                'verbose_name_plural': 'Типы отсутствий',
            },
        ),
    ]
