# Generated by Django 6.0.1 on 2026-02-18 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absencerecord',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'judge'}, on_delete=django.db.models.deletion.CASCADE, related_name='absence_records', to=settings.AUTH_USER_MODEL, verbose_name='Судья'),
        ),
        migrations.AddField(
            model_name='absencerecord',
            name='absence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personnel.absencetype', verbose_name='Тип отсутствия'),
        ),
    ]
