# Generated by Django 4.2.7 on 2025-12-09 08:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_card', '0001_initial'),
        ('criminal_proceedings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10, unique=True, verbose_name='Индекс')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование индекса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Индекс регистрации',
                'verbose_name_plural': 'Индексы регистрации',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='RegistryCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.PositiveIntegerField(default=0, verbose_name='Текущий номер')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Последнее использование')),
                ('total_registered', models.PositiveIntegerField(default=0, verbose_name='Всего зарегистрировано')),
                ('index', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counter', to='case_registry.registryindex', verbose_name='Индекс')),
            ],
            options={
                'verbose_name': 'Счетчик регистрации',
                'verbose_name_plural': 'Счетчики регистрации',
            },
        ),
        migrations.CreateModel(
            name='RegisteredCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.PositiveIntegerField(verbose_name='Номер дела')),
                ('full_number', models.CharField(max_length=100, unique=True, verbose_name='Полный номер дела')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание дела')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('archived', 'В архиве'), ('deleted', 'Удалено')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('business_card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_case', to='business_card.businesscard', verbose_name='Базовая карточка')),
                ('criminal_proceedings', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_case', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='case_registry.registryindex', verbose_name='Индекс')),
            ],
            options={
                'verbose_name': 'Зарегистрированное дело',
                'verbose_name_plural': 'Зарегистрированные дела',
                'ordering': ['-registration_date', '-case_number'],
            },
        ),
        migrations.CreateModel(
            name='NumberAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_number', models.PositiveIntegerField(verbose_name='Старый номер')),
                ('new_number', models.PositiveIntegerField(verbose_name='Новый номер')),
                ('reason', models.TextField(verbose_name='Причина корректировки')),
                ('adjusted_by', models.CharField(max_length=255, verbose_name='Кто выполнил корректировку')),
                ('adjusted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата корректировки')),
                ('case_affected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_registry.registeredcase', verbose_name='Затронутое дело')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='case_registry.registryindex', verbose_name='Индекс')),
            ],
            options={
                'verbose_name': 'Корректировка нумерации',
                'verbose_name_plural': 'Корректировки нумерации',
                'ordering': ['-adjusted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='registeredcase',
            index=models.Index(fields=['index', 'case_number'], name='case_regist_index_i_85a396_idx'),
        ),
        migrations.AddIndex(
            model_name='registeredcase',
            index=models.Index(fields=['full_number'], name='case_regist_full_nu_45cf2d_idx'),
        ),
        migrations.AddIndex(
            model_name='registeredcase',
            index=models.Index(fields=['status'], name='case_regist_status_e81e1f_idx'),
        ),
    ]
