# Generated by Django 6.0.1 on 2026-01-27 13:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_number', models.PositiveIntegerField(verbose_name='Старый номер')),
                ('new_number', models.PositiveIntegerField(verbose_name='Новый номер')),
                ('reason', models.TextField(verbose_name='Причина корректировки')),
                ('adjusted_by', models.CharField(max_length=255, verbose_name='Кто выполнил корректировку')),
                ('adjusted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата корректировки')),
            ],
            options={
                'verbose_name': 'Корректировка нумерации',
                'verbose_name_plural': 'Корректировки нумерации',
                'ordering': ['-adjusted_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistryCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.PositiveIntegerField(default=0, verbose_name='Текущий номер')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Последнее использование')),
                ('total_registered', models.PositiveIntegerField(default=0, verbose_name='Всего зарегистрировано')),
            ],
            options={
                'verbose_name': 'Счетчик регистрации',
                'verbose_name_plural': 'Счетчики регистрации',
            },
        ),
        migrations.CreateModel(
            name='RegistryIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10, unique=True, verbose_name='Индекс')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование индекса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Индекс регистрации',
                'verbose_name_plural': 'Индексы регистрации',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondence_type', models.CharField(choices=[('incoming', 'Входящая'), ('outgoing', 'Исходящая')], max_length=20, verbose_name='Тип корреспонденции')),
                ('registration_number', models.CharField(max_length=100, unique=True, verbose_name='Регистрационный номер')),
                ('number_sender_document', models.CharField(blank=True, max_length=100, null=True, verbose_name='Исх. номер документа отправителя')),
                ('outgoing_date_document', models.DateField(blank=True, max_length=100, null=True, verbose_name='Исх. дата документа отправителя')),
                ('method_of_receipt', models.CharField(blank=True, choices=[('purpose', 'Нарочно'), ('e-mail', 'Электронной почтой'), ('mail', 'Почтовой корреспонденцией')], max_length=20, null=True, verbose_name='Способ получения/отправки')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('sender', models.CharField(blank=True, default='', max_length=500, verbose_name='Отправитель')),
                ('recipient', models.CharField(blank=True, default='', max_length=500, verbose_name='Получатель')),
                ('execution_deadline', models.DateField(blank=True, null=True, verbose_name='Срок исполнения')),
                ('executor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнитель')),
                ('actual_execution_date', models.DateField(blank=True, null=True, verbose_name='Дата исполнения')),
                ('document_type', models.CharField(max_length=200, verbose_name='Тип документа')),
                ('summary', models.TextField(verbose_name='Краткое содержание')),
                ('pages_count', models.PositiveIntegerField(default=1, verbose_name='Количество листов')),
                ('status', models.CharField(choices=[('received', 'Получено'), ('registered', 'Зарегистрировано'), ('processed', 'Обработано'), ('sent', 'Отправлено'), ('archived', 'В архиве')], default='received', max_length=20, verbose_name='Статус')),
                ('attached_files', models.FileField(blank=True, null=True, upload_to='correspondence/', verbose_name='Прикрепленные файлы')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondence', to='business_card.businesscard', verbose_name='Связанная карточка дела')),
            ],
            options={
                'verbose_name': 'Корреспонденция',
                'verbose_name_plural': 'Корреспонденция',
                'ordering': ['-registration_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrespondenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('incoming_counter', models.PositiveIntegerField(default=0, verbose_name='Счетчик входящей')),
                ('outgoing_counter', models.PositiveIntegerField(default=0, verbose_name='Счетчик исходящей')),
            ],
            options={
                'verbose_name': 'Счетчик корреспонденции',
                'verbose_name_plural': 'Счетчики корреспонденции',
                'unique_together': {('year',)},
            },
        ),
        migrations.CreateModel(
            name='RegisteredCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.PositiveIntegerField(verbose_name='Номер дела')),
                ('full_number', models.CharField(max_length=100, unique=True, verbose_name='Полный номер дела')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание дела')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('archived', 'В архиве'), ('deleted', 'Удалено')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('business_card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_case', to='business_card.businesscard', verbose_name='Базовая карточка')),
            ],
            options={
                'verbose_name': 'Зарегистрированное дело',
                'verbose_name_plural': 'Зарегистрированные дела',
                'ordering': ['-registration_date', '-case_number'],
            },
        ),
    ]
