# Generated by Django 6.0.1 on 2026-02-18 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_registry', '0001_initial'),
        ('civil_proceedings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredcase',
            name='civil_proceedings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='civil_proceedings.civilproceedings', verbose_name='Гражданское производство'),
        ),
    ]
