# Generated by Django 6.0.1 on 2026-01-27 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_registry', '0001_initial'),
        ('criminal_proceedings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredcase',
            name='criminal_proceedings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_case', to='criminal_proceedings.criminalproceedings', verbose_name='Уголовное производство'),
        ),
        migrations.AddField(
            model_name='numberadjustment',
            name='case_affected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_registry.registeredcase', verbose_name='Затронутое дело'),
        ),
        migrations.AddField(
            model_name='registrycounter',
            name='index',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counter', to='case_registry.registryindex', verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='registeredcase',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='case_registry.registryindex', verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='numberadjustment',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='case_registry.registryindex', verbose_name='Индекс'),
        ),
        migrations.AddIndex(
            model_name='correspondence',
            index=models.Index(fields=['correspondence_type', 'registration_date'], name='case_regist_corresp_96fdf7_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondence',
            index=models.Index(fields=['registration_number'], name='case_regist_registr_38f065_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondence',
            index=models.Index(fields=['status'], name='case_regist_status_deee43_idx'),
        ),
        migrations.AddIndex(
            model_name='registeredcase',
            index=models.Index(fields=['index', 'case_number'], name='case_regist_index_i_85a396_idx'),
        ),
        migrations.AddIndex(
            model_name='registeredcase',
            index=models.Index(fields=['full_number'], name='case_regist_full_nu_45cf2d_idx'),
        ),
        migrations.AddIndex(
            model_name='registeredcase',
            index=models.Index(fields=['status'], name='case_regist_status_e81e1f_idx'),
        ),
    ]
