# Generated by Django 6.0.1 on 2026-03-02 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_registry', '0001_initial'),
        ('civil_proceedings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondence',
            name='civil_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondence', to='civil_proceedings.civilproceedings', verbose_name='Связанное гражданское дело'),
        ),
    ]
