# Generated by Django 4.2.7 on 2025-12-22 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_initial'),
        ('case_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrespondenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('incoming_counter', models.PositiveIntegerField(default=0, verbose_name='Счетчик входящей')),
                ('outgoing_counter', models.PositiveIntegerField(default=0, verbose_name='Счетчик исходящей')),
            ],
            options={
                'verbose_name': 'Счетчик корреспонденции',
                'verbose_name_plural': 'Счетчики корреспонденции',
                'unique_together': {('year',)},
            },
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondence_type', models.CharField(choices=[('incoming', 'Входящая'), ('outgoing', 'Исходящая')], max_length=20, verbose_name='Тип корреспонденции')),
                ('registration_number', models.CharField(max_length=100, unique=True, verbose_name='Регистрационный номер')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('sender', models.CharField(max_length=500, verbose_name='Отправитель')),
                ('recipient', models.CharField(max_length=500, verbose_name='Получатель')),
                ('document_type', models.CharField(max_length=200, verbose_name='Тип документа')),
                ('summary', models.TextField(verbose_name='Краткое содержание')),
                ('pages_count', models.PositiveIntegerField(default=1, verbose_name='Количество листов')),
                ('status', models.CharField(choices=[('received', 'Получено'), ('registered', 'Зарегистрировано'), ('processed', 'Обработано'), ('sent', 'Отправлено'), ('archived', 'В архиве')], default='received', max_length=20, verbose_name='Статус')),
                ('attached_files', models.FileField(blank=True, null=True, upload_to='correspondence/', verbose_name='Прикрепленные файлы')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondence', to='business_card.businesscard', verbose_name='Связанная карточка дела')),
            ],
            options={
                'verbose_name': 'Корреспонденция',
                'verbose_name_plural': 'Корреспонденция',
                'ordering': ['-registration_date', '-created_at'],
                'indexes': [models.Index(fields=['correspondence_type', 'registration_date'], name='case_regist_corresp_96fdf7_idx'), models.Index(fields=['registration_number'], name='case_regist_registr_38f065_idx'), models.Index(fields=['status'], name='case_regist_status_deee43_idx')],
            },
        ),
    ]
