# Generated by Django 4.2.7 on 2025-12-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_registry', '0002_correspondencecounter_correspondence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='recipient',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='sender',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Отправитель'),
        ),
    ]
