# Generated by Django 6.0.1 on 2026-02-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_registry', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Регистрационный номер'),
        ),
    ]
