# Generated by Django 5.2.9 on 2025-12-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_registry', '0003_alter_correspondence_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondence',
            name='actual_execution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата исполнения'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='execution_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок исполнения'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='executor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='method_of_receipt',
            field=models.CharField(blank=True, choices=[('purpose', 'Нарочно'), ('e-mail', 'Электронной почтой'), ('mail', 'Почтовой корреспонденцией')], max_length=20, null=True, verbose_name='Способ получения/отправки'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='number_sender_document',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Исх. номер документа отправителя'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='outgoing_date_document',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Исх. дата документа отправителя'),
        ),
    ]
