# Generated by Django 6.0 on 2025-12-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_registry', '0004_correspondence_actual_execution_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='outgoing_date_document',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Исх. дата документа отправителя'),
        ),
    ]
