# Generated by Django 6.0.1 on 2026-03-03 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_category', models.CharField(choices=[('criminal', 'Уголовные'), ('admin_offense', 'Административные правонарушения (КОАП)'), ('civil', 'Гражданские'), ('kas', 'Административное судопроизводство (КАС)'), ('common', 'Общие для всех')], help_text='Для какого типа дел предназначен этот шаблон', max_length=20, verbose_name='Категория дела')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, help_text='Для чего нужен этот документ', verbose_name='Описание')),
                ('template_file', models.FileField(blank=True, help_text='Загрузите файл шаблона (например, в формате .docx)', null=True, upload_to='document_templates/', verbose_name='Файл шаблона')),
                ('is_active', models.BooleanField(default=True, help_text='Отображается ли этот шаблон для выбора', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['case_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID дела')),
                ('title', models.CharField(help_text='Например: Постановление о назначении экспертизы по делу №123', max_length=500, verbose_name='Заголовок документа')),
                ('content', models.TextField(help_text='Текст документа. Здесь можно будет использовать HTML или другой формат.', verbose_name='Содержимое документа')),
                ('generated_file', models.FileField(blank=True, help_text='Файл, сгенерированный из шаблона (например, .docx или .pdf)', null=True, upload_to='generated_documents/%Y/%m/', verbose_name='Сгенерированный файл')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('signed', 'Подписан')], default='draft', max_length=10, verbose_name='Статус')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время подписания')),
                ('signature_text', models.TextField(blank=True, help_text='Сгенерированный текст подписи (например, с датой и ФИО)', verbose_name='Текст подписи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('criminalproceedings', 'administrativeproceedings', 'civilproceedings', 'kasproceedings')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип дела')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Подписал')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='case_documents.documenttemplate', verbose_name='Шаблон документа')),
            ],
            options={
                'verbose_name': 'Документ дела',
                'verbose_name_plural': 'Документы дел',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='case_docume_content_8e5475_idx'), models.Index(fields=['status'], name='case_docume_status_6d3f0d_idx'), models.Index(fields=['-created_at'], name='case_docume_created_4128eb_idx')],
            },
        ),
    ]
