# Generated by Django 6.0.1 on 2026-04-22 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Подписал'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='case_documents.documenttemplate', verbose_name='Шаблон документа'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['content_type', 'object_id'], name='case_docume_content_8e5475_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['status'], name='case_docume_status_6d3f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['-created_at'], name='case_docume_created_4128eb_idx'),
        ),
    ]
