# Generated by Django 6.0.1 on 2026-01-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_appeal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Апелляционное решение')),
            ],
            options={
                'verbose_name': 'Апелляция',
                'verbose_name_plural': 'Апелляции',
            },
        ),
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=100, unique=True, verbose_name='номер дела')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания/изменения карточки')),
                ('preliminary_hearing', models.DateField(blank=True, null=True, verbose_name='Дата предварительного слушания/(с/з)')),
                ('name_case', models.CharField(max_length=200, verbose_name='Решение по поступившему делу')),
            ],
            options={
                'verbose_name': 'Карточка на дело',
                'verbose_name_plural': 'карточка на дело',
                'ordering': ('pub_date',),
            },
        ),
        migrations.CreateModel(
            name='BusinessMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_meeting', models.DateField(verbose_name='Дата заседания')),
                ('meeting_time', models.TimeField(verbose_name='Время заседания')),
                ('composition_colleges', models.CharField(blank=True, max_length=50, null=True, verbose_name='Состав коллегии')),
                ('result_court_session', models.CharField(blank=True, max_length=200, null=True, verbose_name='Результат судебного заседания')),
                ('reason_deposition', models.CharField(blank=True, max_length=200, null=True, verbose_name='причина отложения')),
            ],
            options={
                'verbose_name': 'Новое дело',
                'verbose_name_plural': 'Новое дело',
                'ordering': ('date_meeting',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.CharField(max_length=200, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Категория дела',
                'verbose_name_plural': 'Категория дела',
                'ordering': ('title_category',),
            },
        ),
        migrations.CreateModel(
            name='ConsideredCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consideration', models.DateField(verbose_name='Дата рассмотрения')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='дата вступления в законную силу')),
                ('executive_lists', models.DateField(blank=True, null=True, verbose_name='Дата исполнения дела')),
            ],
            options={
                'verbose_name': 'Дело рассмотренно',
            },
        ),
        migrations.CreateModel(
            name='Decisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_case', models.CharField(max_length=200, verbose_name='Решение по поступившему делу')),
                ('date_consideration', models.DateField(blank=True, null=True, verbose_name='Дата вынесения')),
                ('notation', models.TextField(blank=True, max_length=300, null=True, verbose_name='примечания')),
            ],
            options={
                'verbose_name': 'Вынесенное решение',
                'verbose_name_plural': 'Вынесенные решения',
                'ordering': ('date_consideration',),
            },
        ),
        migrations.CreateModel(
            name='ExecutionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_notification', models.DateField(verbose_name='Дата уведомления')),
                ('executive_lists', models.DateField(blank=True, null=True, verbose_name='Дата исполнения дела')),
            ],
            options={
                'verbose_name': 'Дело рассмотрено',
            },
        ),
        migrations.CreateModel(
            name='FamiliarizationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petition', models.BooleanField(verbose_name='заявлено ходатайство об ознакомлении')),
                ('start_date', models.DateField(verbose_name='дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='дата окончания')),
                ('number_days', models.IntegerField(blank=True, null=True, verbose_name='количество дней')),
                ('amount_one_day', models.IntegerField(blank=True, null=True, verbose_name='сумма за один день ознакомления')),
                ('total_amount', models.IntegerField(blank=True, null=True, verbose_name='общая сумма вознаграждения по постановлению')),
            ],
            options={
                'verbose_name': 'Ознакомление с материаламми дела',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_firm_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название адвокатского образования')),
                ('law_firm_address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('law_firm_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон ')),
                ('law_firm_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование банка')),
                ('bank_bik', models.CharField(blank=True, max_length=20, null=True, verbose_name='БИК банка')),
                ('correspondent_account', models.CharField(blank=True, max_length=30, null=True, verbose_name='Корреспондентский счет')),
                ('payment_account', models.CharField(blank=True, max_length=30, null=True, verbose_name='Расчетный счет')),
                ('lawyer_certificate_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер адвокатского удостоверения')),
                ('lawyer_certificate_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи удостоверения')),
                ('days_for_payment', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество дней для оплаты')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Сумма оплаты (руб.)')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата постановления об оплате')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Адвокат',
                'verbose_name_plural': 'Адвокаты',
            },
        ),
        migrations.CreateModel(
            name='Petitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petitions', models.CharField(max_length=150, verbose_name='наименование ходатайства')),
            ],
            options={
                'verbose_name': 'Ходатайство',
                'verbose_name_plural': 'Ходатайства',
                'ordering': ('petitions',),
            },
        ),
        migrations.CreateModel(
            name='PetitionsInCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_application', models.DateField(verbose_name='Дата ходатайства')),
                ('date_decision', models.DateField(null=True, verbose_name='Дата решения по ходатайству')),
                ('notation', models.TextField(max_length=300, null=True, verbose_name='примечания')),
            ],
            options={
                'verbose_name': 'Ходатайство',
                'verbose_name_plural': 'Ходатайства',
                'ordering': ('date_application',),
            },
        ),
        migrations.CreateModel(
            name='SidesCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sides_case', models.CharField(max_length=100, verbose_name='Сторона по делу')),
            ],
            options={
                'verbose_name': 'Сторона по делу',
                'verbose_name_plural': 'Стороны по делу',
                'ordering': ('sides_case',),
            },
        ),
        migrations.CreateModel(
            name='SidesCaseInCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО / Наименование')),
                ('status', models.CharField(choices=[('individual', 'Физическое лицо'), ('legal', 'Юридическое лицо'), ('government', 'Орган власти'), ('other', 'Иное')], default='individual', max_length=20, verbose_name='Статус лица')),
                ('date_sending_agenda', models.DateField(blank=True, null=True, verbose_name='Дата направления повестки')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, null=True, verbose_name='Пол')),
                ('document_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Документ удостоверяющий личность')),
                ('document_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер документа')),
                ('document_series', models.CharField(blank=True, max_length=20, null=True, verbose_name='Серия документа')),
                ('document_issued_by', models.TextField(blank=True, null=True, verbose_name='Кем выдан документ')),
                ('document_issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи документа')),
                ('inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, null=True, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ОГРН')),
                ('legal_address', models.TextField(blank=True, null=True, verbose_name='Юридический адрес')),
                ('director_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО руководителя')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес проживания/нахождения')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Сторона по делу',
                'verbose_name_plural': 'Стороны по делу',
            },
        ),
    ]
