# Generated by Django 4.2.7 on 2025-09-03 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Автор карточки'),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='case_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='business_card.category', verbose_name='Категория дела'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='business_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='business_card.businesscard', verbose_name='Карточка на дело'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='notification_parties',
            field=models.ManyToManyField(to='business_card.sidescaseincase', verbose_name='Уведомление сторон об апелляции'),
        ),
    ]
