# Generated by Django 6.0.1 on 2026-01-27 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_card', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Автор карточки'),
        ),
        migrations.AddField(
            model_name='businessmovement',
            name='business_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessmovement', to='business_card.businesscard', verbose_name='Карточка на дело'),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='case_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='business_card.category', verbose_name='Категория дела'),
        ),
        migrations.AddField(
            model_name='consideredcase',
            name='business_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consideredcase', to='business_card.businesscard', verbose_name='Карточка на дело'),
        ),
        migrations.AddField(
            model_name='consideredcase',
            name='name_case',
            field=models.ManyToManyField(to='business_card.decisions', verbose_name='Решение по делу'),
        ),
        migrations.AddField(
            model_name='businessmovement',
            name='decision_case',
            field=models.ManyToManyField(to='business_card.decisions', verbose_name='Решение по поступившему делу'),
        ),
        migrations.AddField(
            model_name='executioncase',
            name='business_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executioncase', to='business_card.businesscard', verbose_name='Карточка на дело'),
        ),
        migrations.AddField(
            model_name='familiarizationcase',
            name='business_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiarizationcase', to='business_card.businesscard', verbose_name='Карточка на дело'),
        ),
        migrations.AddField(
            model_name='petitionsincase',
            name='business_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitionsincase', to='business_card.businesscard', verbose_name='Карточка на дело'),
        ),
        migrations.AddField(
            model_name='petitionsincase',
            name='decision_rendered',
            field=models.ManyToManyField(to='business_card.decisions', verbose_name='наименование вынесенного решения'),
        ),
        migrations.AddField(
            model_name='petitionsincase',
            name='petitions_name',
            field=models.ManyToManyField(to='business_card.petitions', verbose_name='ходатайства по делу'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='business_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidescaseincase', to='business_card.businesscard', verbose_name='Карточка на дело'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='sides_case',
            field=models.ManyToManyField(to='business_card.sidescase', verbose_name='Стороны по делу'),
        ),
        migrations.AddField(
            model_name='petitionsincase',
            name='notification_parties',
            field=models.ManyToManyField(to='business_card.sidescaseincase', verbose_name='Кто заявил ходатайство'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='sides_case_incase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_info', to='business_card.sidescaseincase', verbose_name='Сторона (адвокат)'),
        ),
        migrations.AddField(
            model_name='familiarizationcase',
            name='notification_parties',
            field=models.ManyToManyField(to='business_card.sidescaseincase', verbose_name='Кто заявил ходатайство'),
        ),
        migrations.AddField(
            model_name='executioncase',
            name='notification_parties',
            field=models.ManyToManyField(to='business_card.sidescaseincase', verbose_name='Уведомление сторон об исполнении'),
        ),
        migrations.AddField(
            model_name='consideredcase',
            name='notification_parties',
            field=models.ManyToManyField(to='business_card.sidescaseincase', verbose_name='Уведомление сторон'),
        ),
        migrations.AddIndex(
            model_name='sidescaseincase',
            index=models.Index(fields=['name'], name='business_ca_name_ca34b3_idx'),
        ),
        migrations.AddIndex(
            model_name='sidescaseincase',
            index=models.Index(fields=['inn'], name='business_ca_inn_d50b39_idx'),
        ),
        migrations.AddIndex(
            model_name='sidescaseincase',
            index=models.Index(fields=['status'], name='business_ca_status_fda742_idx'),
        ),
    ]
