# Generated by Django 4.2.7 on 2025-02-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petitionsincase',
            name='decision_rendered',
        ),
        migrations.AddField(
            model_name='petitionsincase',
            name='decision_rendered',
            field=models.ManyToManyField(to='business_card.decisions', verbose_name='наименование вынесенного решения'),
        ),
    ]
