# Generated by Django 4.2.7 on 2025-10-13 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Автор карточки'),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='case_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='business_card.category', verbose_name='Категория дела'),
        ),
    ]
