# Generated by Django 5.2.9 on 2026-01-21 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_firm_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название адвокатского образования')),
                ('law_firm_address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('law_firm_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон ')),
                ('law_firm_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование банка')),
                ('bank_bik', models.CharField(blank=True, max_length=20, null=True, verbose_name='БИК банка')),
                ('correspondent_account', models.CharField(blank=True, max_length=30, null=True, verbose_name='Корреспондентский счет')),
                ('payment_account', models.CharField(blank=True, max_length=30, null=True, verbose_name='Расчетный счет')),
                ('lawyer_certificate_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер адвокатского удостоверения')),
                ('lawyer_certificate_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи удостоверения')),
                ('days_for_payment', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество дней для оплаты')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Сумма оплаты (руб.)')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата постановления об оплате')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Адвокат',
                'verbose_name_plural': 'Адвокаты',
            },
        ),
        migrations.AlterModelOptions(
            name='sidescaseincase',
            options={'verbose_name': 'Сторона по делу', 'verbose_name_plural': 'Стороны по делу'},
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес проживания/нахождения'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='director_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО руководителя'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='document_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи документа'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='document_issued_by',
            field=models.TextField(blank=True, null=True, verbose_name='Кем выдан документ'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер документа'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='document_series',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Серия документа'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Документ удостоверяющий личность'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='inn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='kpp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='legal_address',
            field=models.TextField(blank=True, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='ogrn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='sidescaseincase',
            name='status',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('legal', 'Юридическое лицо'), ('government', 'Орган власти'), ('other', 'Иное')], default='individual', max_length=20, verbose_name='Статус лица'),
        ),
        migrations.AlterField(
            model_name='sidescaseincase',
            name='business_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidescaseincase', to='business_card.businesscard', verbose_name='Карточка на дело'),
        ),
        migrations.AlterField(
            model_name='sidescaseincase',
            name='name',
            field=models.CharField(max_length=150, verbose_name='ФИО / Наименование'),
        ),
        migrations.AddIndex(
            model_name='sidescaseincase',
            index=models.Index(fields=['name'], name='business_ca_name_ca34b3_idx'),
        ),
        migrations.AddIndex(
            model_name='sidescaseincase',
            index=models.Index(fields=['inn'], name='business_ca_inn_d50b39_idx'),
        ),
        migrations.AddIndex(
            model_name='sidescaseincase',
            index=models.Index(fields=['status'], name='business_ca_status_fda742_idx'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='sides_case_incase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_info', to='business_card.sidescaseincase', verbose_name='Сторона (адвокат)'),
        ),
    ]
