# Generated by Django 4.2.7 on 2025-09-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='business_card',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='date_appeal',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='meeting_requirements',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='notification_parties',
        ),
        migrations.AlterField(
            model_name='appeal',
            name='decision_appeal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Апелляционное решение'),
        ),
    ]
