# Generated by Django 6.0.4 on 2026-04-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawyer',
            options={},
        ),
    ]
